const path = {
  main: '/gmzyjc/ok/nk/',
};

const sidebar = [
  { text: '《中医内科学》' },
  {
    text: '编者与编者的话',
    link: `${path.main}nk00`,
    collapsed: true,
    items: [
      { text: '编者', link: `${path.main}nk00-0.1.0.0.0` },
      { text: '编者的话', link: `${path.main}nk00-0.2.0.0.0` },
      { text: '导言', link: `${path.main}daoyan` },
    ],
  },
  {
    text: '总论',
    link: `${path.main}nk0zl00`,
    collapsed: true,
    items: [
      { text: '第一章 中医内科的源流与发展', link: `${path.main}nk0zl01` },
      { text: '第二章 辨识内科病证规律的方法', link: `${path.main}nk0zl02` },
      { text: '第三章 治疗内科病证的原则与方法', link: `${path.main}nk0zl03` },
      { text: '第四章 中医内科学的学习方法', link: `${path.main}nk0zl04` },
    ],
  },
  {
    text: '各论',
    link: `${path.main}nkgl01`,
    collapsed: true,
    items: [
      {
        text: '第一章风火燥湿痰病证门',
        link: `${path.main}nkgl01-1.0.0.0.0`,
        collapsed: true,
        items: [
          { text: '感冒', link: `${path.main}nkgl01-1.1.0.0.0` },
          { text: '中风', link: `${path.main}nkgl01-1.2.0.0.0` },
          { text: '痉病', link: `${path.main}nkgl01-1.3.0.0.0` },
          { text: '头痛', link: `${path.main}nkgl01-1.4.0.0.0` },
          { text: '眩晕', link: `${path.main}nkgl01-1.5.0.0.0` },
          { text: '颤证', link: `${path.main}nkgl01-1.6.0.0.0` },
          { text: '内伤发热', link: `${path.main}nkgl01-1.7.0.0.0` },
          { text: '消渴', link: `${path.main}nkgl01-1.8.0.0.0` },
          { text: '水肿', link: `${path.main}nkgl01-1.9.0.0.0` },
          { text: '湿阻', link: `${path.main}nkgl01-1.10.0.0.0` },
          { text: '痰饮', link: `${path.main}nkgl01-1.11.0.0.0` },
          { text: '疟疾', link: `${path.main}nkgl01-1.12.0.0.0` },
        ],
      },
      {
        text: '第二章气血津液病证门',
        link: `${path.main}nkgl02`,
        collapsed: true,
        items: [
          { text: '郁证', link: `${path.main}nkgl02-0.1.0.0.0` },
          { text: '梅核气', link: `${path.main}nkgl02-0.2.0.0.0` },
          { text: '奔豚气', link: `${path.main}nkgl02-0.3.0.0.0` },
          { text: '积聚', link: `${path.main}nkgl02-0.4.0.0.0` },
          { text: '虚劳', link: `${path.main}nkgl02-0.5.0.0.0` },
          { text: '咳血', link: `${path.main}nkgl02-0.6.0.0.0` },
          { text: '吐血', link: `${path.main}nkgl02-0.7.0.0.0` },
          {
            text: '鼻衄  附：齿衄',
            link: `${path.main}nkgl02-0.8.0.0.0`,
            collapsed: true,
            items: [{ text: '附：齿衄', link: `${path.main}nkgl02-0.8.1.0.0` }],
          },
          { text: '便血', link: `${path.main}nkgl02-0.9.0.0.0` },
          { text: '尿血', link: `${path.main}nkgl02-0.10.0.0.0` },
          { text: '紫斑', link: `${path.main}nkgl02-0.11.0.0.0` },
          { text: '瘿病', link: `${path.main}nkgl02-0.12.0.0.0` },
        ],
      },
      {
        text: '第三章神志病证门',
        link: `${path.main}nkgl03`,
        collapsed: true,
        items: [
          { text: '神昏', link: `${path.main}nkgl03-0.1.0.0.0` },
          { text: '昏厥', link: `${path.main}nkgl03-0.2.0.0.0` },
          {
            text: '不寐      附：多寐',
            link: `${path.main}nkgl03-0.3.0.0.0`,
            collapsed: true,
            items: [{ text: '附：多寐', link: `${path.main}nkgl03-0.3.1.0.0` }],
          },
          { text: '癫狂', link: `${path.main}nkgl03-0.4.0.0.0` },
          { text: '痫证', link: `${path.main}nkgl03-0.5.0.0.0` },
        ],
      },
      {
        text: '第四章 脏腑病证门',
        link: `${path.main}nkgl04`,
        collapsed: true,
        items: [
          { text: '心悸', link: `${path.main}nkgl04-0.1.0.0.0` },
          { text: '心痛', link: `${path.main}nkgl04-0.2.0.0.0` },
          { text: '咳嗽', link: `${path.main}nkgl04-0.3.0.0.0` },
          { text: '肺痿', link: `${path.main}nkgl04-0.4.0.0.0` },
          { text: '肺痈', link: `${path.main}nkgl04-0.5.0.0.0` },
          { text: '肺胀', link: `${path.main}nkgl04-0.6.0.0.0` },
          { text: '喘证', link: `${path.main}nkgl04-0.7.0.0.0` },
          { text: '哮证', link: `${path.main}nkgl04-0.8.0.0.0` },
          { text: '肺痨', link: `${path.main}nkgl04-0.9.0.0.0` },
          {
            text: '胃痛',
            link: `${path.main}nkgl04-0.10.0.0.0`,
            collapsed: true,
            items: [
              { text: '附：吐酸', link: `${path.main}nkgl04-0.10.1.0.0` },
              { text: '附：嘈杂', link: `${path.main}nkgl04-0.10.2.0.0` },
            ],
          },
          {
            text: '呕吐',
            link: `${path.main}nkgl04-0.11.0.0.0`,
            collapsed: true,
            items: [{ text: '附：嗳气', link: `${path.main}nkgl04-0.11.1.0.0` }],
          },
          { text: '霍乱', link: `${path.main}nkgl04-0.12.0.0.0` },
          { text: '噎膈', link: `${path.main}nkgl04-0.13.0.0.0` },
          { text: '反胃', link: `${path.main}nkgl04-0.14.0.0.0` },
          { text: '呃逆', link: `${path.main}nkgl04-0.15.0.0.0` },
          { text: '痞满', link: `${path.main}nkgl04-0.16.0.0.0` },
          { text: '泄泻', link: `${path.main}nkgl04-0.17.0.0.0` },
          { text: '痢疾', link: `${path.main}nkgl04-0.18.0.0.0` },
          { text: '便秘', link: `${path.main}nkgl04-0.19.0.0.0` },
          { text: '腹胀', link: `${path.main}nkgl04-0.20.0.0.0` },
          { text: '黄疸', link: `${path.main}nkgl04-0.21.0.0.0` },
          { text: '臌胀', link: `${path.main}nkgl04-0.22.0.0.0` },
          { text: '遗尿', link: `${path.main}nkgl04-0.23.0.0.0` },
          { text: '遗精', link: `${path.main}nkgl04-0.24.0.0.0` },
          { text: '阳痿', link: `${path.main}nkgl04-0.25.0.0.0` },
          { text: '淋证', link: `${path.main}nkgl04-0.26.0.0.0` },
          { text: '癃闭', link: `${path.main}nkgl04-0.27.0.0.0` },
          { text: '关格', link: `${path.main}nkgl04-0.28.0.0.0` },
        ],
      },
      {
        text: '第五章身形病证门',
        link: `${path.main}nkgl05`,
        collapsed: true,
        items: [
          { text: '痹证', link: `${path.main}nkgl05-0.1.0.0.0` },
          { text: '痿证', link: `${path.main}nkgl05-0.2.0.0.0` },
          { text: '胸痹', link: `${path.main}nkgl05-0.3.0.0.0` },
          { text: '胁痛', link: `${path.main}nkgl05-0.4.0.0.0` },
          { text: '腰痛', link: `${path.main}nkgl05-0.5.0.0.0` },
          { text: '腹痛', link: `${path.main}nkgl05-0.6.0.0.0` },
          { text: '肩背痛', link: `${path.main}nkgl05-0.7.0.0.0` },
          { text: '口眼歪斜', link: `${path.main}nkgl05-0.8.0.0.0` },
          { text: '四肢麻木', link: `${path.main}nkgl05-0.9.0.0.0` },
        ],
      },
      {
        text: '第六章   虫病证门',
        link: `${path.main}nkgl06`,
        collapsed: true,
        items: [
          { text: '蛔虫病', link: `${path.main}nkgl06-0.1.0.0.0` },
          { text: '蛲虫病', link: `${path.main}nkgl06-0.2.0.0.0` },
          { text: '绦虫病', link: `${path.main}nkgl06-0.3.0.0.0` },
          { text: '钩虫病', link: `${path.main}nkgl06-0.4.0.0.0` },
        ],
      },
      {
        text: '第七章     地方病证门',
        link: `${path.main}nkgl07`,
        collapsed: true,
        items: [
          { text: '大骨节病（尰痺）', link: `${path.main}nkgl07-0.1.0.0.0` },
          { text: '地方性氟病（谷痹）', link: `${path.main}nkgl07-0.2.0.0.0` },
          { text: '克山病（阴毒）', link: `${path.main}nkgl07-0.3.0.0.0` },
          { text: '克汀病(胎怯）', link: `${path.main}nkgl07-0.4.0.0.0` },
        ],
      },
      {
        text: '第八章   职业病证门',
        link: `${path.main}nkgl08`,
        collapsed: true,
        items: [
          { text: '砒（砷）中毒', link: `${path.main}nkgl08-0.1.0.0.0` },
          { text: '铅中毒', link: `${path.main}nkgl08-0.2.0.0.0` },
          { text: '氯乙烯中毒', link: `${path.main}nkgl08-0.3.0.0.0` },
          { text: '尘肺(石劳）', link: `${path.main}nkgl08-0.4.0.0.0` },
        ],
      },
      {
        text: '第九章 高原病证门',
        link: `${path.main}nkgl09`,
        collapsed: true,
        items: [
          { text: '常见证治方剂索引', link: `${path.main}nkgl10fjsy` },
          { text: '电子版录入与校对', link: `${path.main}dzb` },
        ],
      },
    ],
  },
];

export { sidebar as nk };
