const path = {
  main: '/gmzyjc/ok/wk/',
};

const sidebar = [
  { text: '《中医外科学》' },
  { text: '编者与编者的话', link: `${path.main}wk00bz`, collapsed: true, items: [] },
  { text: '编者', link: `${path.main}wk00bz-0.1.0.0.0` },
  { text: '编者的话', link: `${path.main}wk00bz-0.2.0.0.0` },
  { text: '导言', link: `${path.main}daoyan` },
  {
    text: '上篇 总论',
    link: `${path.main}wk01`,
    collapsed: true,
    items: [
      { text: '第一章 中医外科学的源流与发展', link: `${path.main}wk01-1.0.0.0.0` },
      { text: '第二章 病因病机', link: `${path.main}wk02` },
      { text: '第三章 四诊在外科学上的运用', link: `${path.main}wk03` },
      { text: '第四章 辨证', link: `${path.main}wk04` },
      {
        text: '第五章治疗',
        link: `${path.main}wk05`,
        collapsed: true,
        items: [
          { text: '第一节内治法', link: `${path.main}wk05-0.1.0.0.0` },
          { text: '第二节外治法', link: `${path.main}wk05-0.2.0.0.0` },
          { text: '第三节常用方剂介绍', link: `${path.main}wk05-0.3.0.0.0` },
        ],
      },
    ],
  },
  {
    text: '下篇 各论',
    link: `${path.main}wk06`,
    collapsed: true,
    items: [
      {
        text: '第六章 疮疡',
        link: `${path.main}wk06-1.0.0.0.0`,
        collapsed: true,
        items: [
          { text: '第一节 疖', link: `${path.main}wk06-1.1.0.0.0` },
          { text: '第二节 疔疮', link: `${path.main}wk06-1.2.0.0.0` },
          { text: '第三节 痈', link: `${path.main}wk06-1.3.0.0.0` },
          { text: '第四节 有头疽', link: `${path.main}wk06-1.4.0.0.0` },
          { text: '第五节 发', link: `${path.main}wk06-1.5.0.0.0` },
          { text: '第六节 无头疽', link: `${path.main}wk06-1.6.0.0.0` },
          { text: '第七节丹毒', link: `${path.main}wk06-1.7.0.0.0` },
          { text: '第八节流注', link: `${path.main}wk06-1.8.0.0.0` },
          { text: '第九节发颐', link: `${path.main}wk06-1.9.0.0.0` },
          { text: '第十节走黄与内陷', link: `${path.main}wk06-1.10.0.0.0` },
          { text: '第十一节流痰', link: `${path.main}wk06-1.11.0.0.0` },
          { text: '第十二节瘰疬', link: `${path.main}wk06-1.12.0.0.0` },
        ],
      },
      {
        text: '第七章 乳病',
        link: `${path.main}wk07`,
        collapsed: true,
        items: [
          { text: '第一节 概论', link: `${path.main}wk07-0.1.0.0.0` },
          { text: '第二节 乳头破碎', link: `${path.main}wk07-0.2.0.0.0` },
          { text: '第三节 乳痈', link: `${path.main}wk07-0.3.0.0.0` },
          { text: '第四节 乳发', link: `${path.main}wk07-0.4.0.0.0` },
          { text: '第五节 乳痨', link: `${path.main}wk07-0.5.0.0.0` },
          { text: '第六节 乳癖', link: `${path.main}wk07-0.6.0.0.0` },
          { text: '第七节 乳腺增生病', link: `${path.main}wk07-0.7.0.0.0` },
          { text: '第八节 乳疬', link: `${path.main}wk07-0.8.0.0.0` },
          { text: '第九节 乳漏', link: `${path.main}wk07-0.9.0.0.0` },
          { text: '第十节 乳衄', link: `${path.main}wk07-0.10.0.0.0` },
        ],
      },
      {
        text: '第八章 瘿',
        link: `${path.main}wk08`,
        collapsed: true,
        items: [
          { text: '第一节 概论', link: `${path.main}wk08-0.1.0.0.0` },
          { text: '第二节 气瘿', link: `${path.main}wk08-0.2.0.0.0` },
          { text: '第三节 肉瘿', link: `${path.main}wk08-0.3.0.0.0` },
          { text: '第四节 瘿痈', link: `${path.main}wk08-0.4.0.0.0` },
          { text: '第五节 石瘿', link: `${path.main}wk08-0.5.0.0.0` },
        ],
      },
      {
        text: '第九章 瘤',
        link: `${path.main}wk09`,
        collapsed: true,
        items: [
          { text: '第一节 概论', link: `${path.main}wk09-0.1.0.0.0` },
          { text: '第二节 气瘤', link: `${path.main}wk09-0.2.0.0.0` },
          { text: '第三节 血瘤', link: `${path.main}wk09-0.3.0.0.0` },
          { text: '第四节 肉瘤', link: `${path.main}wk09-0.4.0.0.0` },
          { text: '第五节 筋瘤', link: `${path.main}wk09-0.5.0.0.0` },
          { text: '第六节 骨瘤', link: `${path.main}wk09-0.6.0.0.0` },
          { text: '第七节 脂瘤', link: `${path.main}wk09-0.7.0.0.0` },
        ],
      },
      {
        text: '第十章 岩',
        link: `${path.main}wk10`,
        collapsed: true,
        items: [
          { text: '第一节 概论', link: `${path.main}wk10-0.1.0.0.0` },
          { text: '第二节 舌菌', link: `${path.main}wk10-0.2.0.0.0` },
          { text: '第三节 茧唇', link: `${path.main}wk10-0.3.0.0.0` },
          { text: '第四节 乳岩', link: `${path.main}wk10-0.4.0.0.0` },
          { text: '第五节 失荣', link: `${path.main}wk10-0.5.0.0.0` },
          { text: '第六节 肾岩', link: `${path.main}wk10-0.6.0.0.0` },
        ],
      },
      {
        text: '第十一章卒腹痛',
        link: `${path.main}wk11`,
        collapsed: true,
        items: [
          { text: '第一节 肠痈', link: `${path.main}wk11-0.1.0.0.0` },
          { text: '第二节胆道系统感染和胆石症', link: `${path.main}wk11-0.2.0.0.0` },
          { text: '第三节急性胰腺炎', link: `${path.main}wk11-0.3.0.0.0` },
          { text: '第四节胆道蛔虫病', link: `${path.main}wk11-0.4.0.0.0` },
          { text: '第五节泌尿道结石', link: `${path.main}wk11-0.5.0.0.0` },
        ],
      },
      {
        text: '第十二章 皮肤病',
        link: `${path.main}wk12`,
        collapsed: true,
        items: [
          { text: '第一节 概论', link: `${path.main}wk12-0.1.0.0.0` },
          { text: '第二节 急性湿疮', link: `${path.main}wk12-0.2.0.0.0` },
          { text: '第三节 慢性湿疮', link: `${path.main}wk12-0.3.0.0.0` },
          { text: '第四节 婴儿湿疮', link: `${path.main}wk12-0.4.0.0.0` },
          { text: '第五节 药物性皮炎', link: `${path.main}wk12-0.5.0.0.0` },
          { text: '第六节 接触性皮炎', link: `${path.main}wk12-0.6.0.0.0` },
          { text: '第七节 日晒疮', link: `${path.main}wk12-0.7.0.0.0` },
          { text: '第八节 瘾疹', link: `${path.main}wk12-0.8.0.0.0` },
          { text: '第九节 风热疮', link: `${path.main}wk12-0.9.0.0.0` },
          { text: '第十节猫眼疮', link: `${path.main}wk12-0.10.0.0.0` },
          { text: '第十一节瓜藤缠', link: `${path.main}wk12-0.11.0.0.0` },
          { text: '第十二节 白疕', link: `${path.main}wk12-0.12.0.0.0` },
          { text: '第十三节 热疮', link: `${path.main}wk12-0.13.0.0.0` },
          { text: '第十四节 蛇串疮', link: `${path.main}wk12-0.14.0.0.0` },
          { text: '第十五节 疣', link: `${path.main}wk12-0.15.0.0.0` },
          { text: '第十六节 脓疱疮', link: `${path.main}wk12-0.16.0.0.0` },
          { text: '第十七节 癣', link: `${path.main}wk12-0.17.0.0.0` },
          { text: '第十八节 风瘙痒', link: `${path.main}wk12-0.18.0.0.0` },
          { text: '第十九节 牛皮癣', link: `${path.main}wk12-0.19.0.0.0` },
          { text: '第二十节 红斑性狼疮', link: `${path.main}wk12-0.20.0.0.0` },
          { text: '第二十一节 白屑风', link: `${path.main}wk12-0.21.0.0.0` },
          { text: '第二十二节 粉刺', link: `${path.main}wk12-0.22.0.0.0` },
          { text: '第二十三节 酒皶鼻', link: `${path.main}wk12-0.23.0.0.0` },
          { text: '第二十四节 油风', link: `${path.main}wk12-0.24.0.0.0` },
          { text: '第二十五节 蛇皮癣', link: `${path.main}wk12-0.25.0.0.0` },
          { text: '第二十六节 疥疮', link: `${path.main}wk12-0.26.0.0.0` },
          { text: '第二十七节 白癜风', link: `${path.main}wk12-0.27.0.0.0` },
        ],
      },
      {
        text: '第十三章 肛门直肠疾病',
        link: `${path.main}wk13`,
        collapsed: true,
        items: [
          { text: '第一节 概论', link: `${path.main}wk13-0.1.0.0.0` },
          { text: '第二节痔', link: `${path.main}wk13-0.2.0.0.0` },
          { text: '第三节肛隐窝炎', link: `${path.main}wk13-0.3.0.0.0` },
          { text: '第四节 肛裂', link: `${path.main}wk13-0.4.0.0.0` },
          { text: '第五节 肛门直肠周围痈疽', link: `${path.main}wk13-0.5.0.0.0` },
          { text: '第六节 肛瘘', link: `${path.main}wk13-0.6.0.0.0` },
          { text: '第七节 脱肛', link: `${path.main}wk13-0.7.0.0.0` },
          { text: '第八节 息肉痔', link: `${path.main}wk13-0.8.0.0.0` },
          { text: '第九节 肛管直肠癌', link: `${path.main}wk13-0.9.0.0.0` },
        ],
      },
      {
        text: '第十四章 男性前阴病',
        link: `${path.main}wk14`,
        collapsed: true,
        items: [
          { text: '笫一节 概论', link: `${path.main}wk14-0.1.0.0.0` },
          { text: '第二节 子痈', link: `${path.main}wk14-0.2.0.0.0` },
          { text: '第三节 子痰', link: `${path.main}wk14-0.3.0.0.0` },
          { text: '第四节 囊痈', link: `${path.main}wk14-0.4.0.0.0` },
          { text: '第五节 脱囊', link: `${path.main}wk14-0.5.0.0.0` },
          { text: '第六节 水疝', link: `${path.main}wk14-0.6.0.0.0` },
          { text: '第七节 阴茎痰核', link: `${path.main}wk14-0.7.0.0.0` },
          { text: '第八节 前列腺炎', link: `${path.main}wk14-0.8.0.0.0` },
          { text: '第九节 前列腺增生症', link: `${path.main}wk14-0.9.0.0.0` },
          { text: '第十节 血精', link: `${path.main}wk14-0.10.0.0.0` },
        ],
      },
      {
        text: '第十五章 外科其它疾病',
        link: `${path.main}wk15`,
        collapsed: true,
        items: [
          { text: '第一节 水火烫伤', link: `${path.main}wk15-0.1.0.0.0` },
          { text: '第二节 冻疮', link: `${path.main}wk15-0.2.0.0.0` },
          { text: '第三节 毒蛇咬伤', link: `${path.main}wk15-0.3.0.0.0` },
          { text: '第四节 破伤风', link: `${path.main}wk15-0.4.0.0.0` },
          { text: '第五节 臁疮', link: `${path.main}wk15-0.5.0.0.0` },
          { text: '第六节 褥疮', link: `${path.main}wk15-0.6.0.0.0` },
          { text: '第七节 脱疽', link: `${path.main}wk15-0.7.0.0.0` },
          { text: '第八节 血栓性静脉炎', link: `${path.main}wk15-0.8.0.0.0` },
        ],
      },
    ],
  },
  { text: '常见证治方剂', link: `${path.main}wk16fjsy` },
  { text: '电子版录入与校对', link: `${path.main}dzb` },
];

export { sidebar as wk };
