const path = {
  main: '/gmzyjc/ok/gk/',
};

const sidebar = [
  { text: '《中医骨伤科学》' },
  { text: '编者与编者的话', link: `${path.main}gk00` },
  { text: '导言', link: `${path.main}daoyan` },
  { text: '第一章 骨伤科学发展简况', link: `${path.main}gk01` },
  {
    text: '第二章 基础理论',
    link: `${path.main}gk02`,
    collapsed: true,
    items: [
      { text: '一、机能解剖学说', link: `${path.main}gk02-0.0.1.0.0` },
      { text: '二、气血学说', link: `${path.main}gk02-0.0.2.0.0` },
      { text: '三、肾主骨学说', link: `${path.main}gk02-0.0.3.0.0` },
      { text: '四、经络、气功学说', link: `${path.main}gk02-0.0.4.0.0` },
      { text: '五、病因病机学说', link: `${path.main}gk02-0.0.5.0.0` },
    ],
  },
  {
    text: '第三章 诊断',
    link: `${path.main}gk03`,
    collapsed: true,
    items: [
      {
        text: '第一节 症状诊断',
        link: `${path.main}gk03-0.1.0.0.0`,
        collapsed: true,
        items: [
          { text: '一、疼痛', link: `${path.main}gk03-0.1.1.0.0` },
          { text: '二、肿胀', link: `${path.main}gk03-0.1.2.0.0` },
          { text: '三、畸形和功能障碍', link: `${path.main}gk03-0.1.3.0.0` },
          { text: '四、瘀血', link: `${path.main}gk03-0.1.4.0.0` },
          { text: '五、亡血', link: `${path.main}gk03-0.1.5.0.0` },
          { text: '六、其他常见的几种症状', link: `${path.main}gk03-0.1.6.0.0` },
        ],
      },
      {
        text: '第二节 四诊',
        link: `${path.main}gk03-0.2.0.0.0`,
        collapsed: true,
        items: [
          { text: '一、望诊', link: `${path.main}gk03-0.2.1.0.0` },
          { text: '二、问诊', link: `${path.main}gk03-0.2.2.0.0` },
          { text: '三、闻诊', link: `${path.main}gk03-0.2.3.0.0` },
          { text: '四、切诊', link: `${path.main}gk03-0.2.4.0.0` },
        ],
      },
      {
        text: '第三节 骨伤科局部检查法',
        link: `${path.main}gk03-0.3.0.0.0`,
        collapsed: true,
        items: [
          { text: '一、检查的基本原则', link: `${path.main}gk03-0.3.1.0.0` },
          { text: '二、检查的注意事项', link: `${path.main}gk03-0.3.2.0.0` },
          { text: '三、检查的主要内容', link: `${path.main}gk03-0.3.3.0.0` },
          { text: '四、人体各关节测量法', link: `${path.main}gk03-0.3.4.0.0` },
          { text: '五、骨伤科专科检查法', link: `${path.main}gk03-0.3.5.0.0` },
          { text: '六、神经系统检查法', link: `${path.main}gk03-0.3.6.0.0` },
        ],
      },
      {
        text: '第四节 辨证诊断',
        link: `${path.main}gk03-0.4.0.0.0`,
        collapsed: true,
        items: [
          { text: '一、伤筋辨证', link: `${path.main}gk03-0.4.1.0.0` },
          { text: '二、伤骨辨证', link: `${path.main}gk03-0.4.2.0.0` },
        ],
      },
      {
        text: '第五节 X线检查诊断法简介',
        link: `${path.main}gk03-0.5.0.0.0`,
        collapsed: true,
        items: [
          { text: '一、骨骼系统的X线检查方法', link: `${path.main}gk03-0.5.1.0.0` },
          { text: '二、骨的发育及正常变异', link: `${path.main}gk03-0.5.2.0.0` },
          { text: '三、骨像异常', link: `${path.main}gk03-0.5.3.0.0` },
        ],
      },
      {
        text: '第六节 物理检查诊断法简介',
        link: `${path.main}gk03-0.6.0.0.0`,
        collapsed: true,
        items: [
          { text: '一、活体组织检查', link: `${path.main}gk03-0.6.1.0.0` },
          { text: '二、同位素扫描', link: `${path.main}gk03-0.6.2.0.0` },
          { text: '三、核磁共振', link: `${path.main}gk03-0.6.3.0.0` },
          { text: '四、关节镜检查', link: `${path.main}gk03-0.6.4.0.0` },
        ],
      },
    ],
  },
  {
    text: '第四章 治疗',
    link: `${path.main}gk04`,
    collapsed: true,
    items: [
      {
        text: '第一节 创伤急救',
        link: `${path.main}gk04-0.1.0.0.0`,
        collapsed: true,
        items: [
          { text: '一、创伤救护', link: `${path.main}gk04-0.1.1.0.0` },
          { text: '二、休克急救', link: `${path.main}gk04-0.1.2.0.0` },
        ],
      },
      {
        text: '第二节 整骨手法',
        link: `${path.main}gk04-0.2.0.0.0`,
        collapsed: true,
        items: [
          { text: '一、手法的概念和基本理论', link: `${path.main}gk04-0.2.1.0.0` },
          { text: '二、手法的作用', link: `${path.main}gk04-0.2.2.0.0` },
          { text: '三、常用手法', link: `${path.main}gk04-0.2.3.0.0` },
          { text: '四、手法的适应症与禁忌症', link: `${path.main}gk04-0.2.4.0.0` },
          { text: '附：清创术', link: `${path.main}gk04-0.2.5.0.0` },
        ],
      },
      {
        text: '第三节 外固定与内固定',
        link: `${path.main}gk04-0.3.0.0.0`,
        collapsed: true,
        items: [
          { text: '一、外固定', link: `${path.main}gk04-0.3.1.0.0` },
          { text: '二、内固定', link: `${path.main}gk04-0.3.2.0.0` },
        ],
      },
      {
        text: '第四节 药物治疗',
        link: `${path.main}gk04-0.4.0.0.0`,
        collapsed: true,
        items: [
          { text: '一、内治法', link: `${path.main}gk04-0.4.1.0.0` },
          { text: '二、外治法', link: `${path.main}gk04-0.4.2.0.0` },
          { text: '第五节 功能锻炼', link: `${path.main}gk04-0.5.0.0.0` },
        ],
      },
    ],
  },
  {
    text: '第五章 骨折与关节脱位',
    link: `${path.main}gk05`,
    collapsed: true,
    items: [
      {
        text: '第一节 骨折概述',
        link: `${path.main}gk05-0.1.0.0.0`,
        collapsed: true,
        items: [
          { text: '一、骨折发生的原因', link: `${path.main}gk05-0.1.1.0.0` },
          { text: '二、骨折的分类', link: `${path.main}gk05-0.1.2.0.0` },
          { text: '三、骨折的愈合过程', link: `${path.main}gk05-0.1.3.0.0` },
          { text: '四、影响骨折愈合的因素', link: `${path.main}gk05-0.1.4.0.0` },
          { text: '五、骨折的并发症及处理', link: `${path.main}gk05-0.1.5.0.0` },
          { text: '六、骨折临床愈合标准', link: `${path.main}gk05-0.1.6.0.0` },
          { text: '七、骨折的治疗原则', link: `${path.main}gk05-0.1.7.0.0` },
        ],
      },
      {
        text: '第二节 上肢骨折',
        link: `${path.main}gk05-0.2.0.0.0`,
        collapsed: true,
        items: [
          { text: '一、锁骨骨折', link: `${path.main}gk05-0.2.1.0.0` },
          { text: '二、肱骨外科颈骨折', link: `${path.main}gk05-0.2.2.0.0` },
          { text: '三、肱骨干骨折', link: `${path.main}gk05-0.2.3.0.0` },
          { text: '四、肱骨髁上骨折', link: `${path.main}gk05-0.2.4.0.0` },
          { text: '五、肱骨髁间骨折', link: `${path.main}gk05-0.2.5.0.0` },
          { text: '六、肱骨外髁骨折', link: `${path.main}gk05-0.2.6.0.0` },
          { text: '七、肱骨内上髁骨折', link: `${path.main}gk05-0.2.7.0.0` },
          { text: '八、尺骨鹰嘴骨折', link: `${path.main}gk05-0.2.8.0.0` },
          { text: '九、尺骨上1/3骨折合并桡骨小头脱位', link: `${path.main}gk05-0.2.9.0.0` },
          { text: '十、尺、桡骨双骨折', link: `${path.main}gk05-0.2.10.0.0` },
          { text: '十一、尺骨干骨折', link: `${path.main}gk05-0.2.11.0.0` },
          { text: '十二、桡骨干骨折', link: `${path.main}gk05-0.2.12.0.0` },
          { text: '十三、桡骨骨折合并下桡尺关节脱位', link: `${path.main}gk05-0.2.13.0.0` },
          { text: '十四、桡骨下端骨折', link: `${path.main}gk05-0.2.14.0.0` },
          { text: '十五、腕舟骨骨折', link: `${path.main}gk05-0.2.15.0.0` },
          { text: '十六、指骨骨折', link: `${path.main}gk05-0.2.16.0.0` },
        ],
      },
      {
        text: '第三节 下肢骨折',
        link: `${path.main}gk05-0.3.0.0.0`,
        collapsed: true,
        items: [
          { text: '一、骨盆骨折', link: `${path.main}gk05-0.3.1.0.0` },
          { text: '二、骶尾骨骨折', link: `${path.main}gk05-0.3.2.0.0` },
          { text: '三、股骨颈骨折', link: `${path.main}gk05-0.3.3.0.0` },
          { text: '四、股骨粗隆部骨折', link: `${path.main}gk05-0.3.4.0.0` },
          { text: '五、股骨干骨折', link: `${path.main}gk05-0.3.5.0.0` },
          { text: '六、髌骨骨折', link: `${path.main}gk05-0.3.6.0.0` },
          { text: '七、胫骨干骨折', link: `${path.main}gk05-0.3.7.0.0` },
          { text: '八、腓骨干骨折', link: `${path.main}gk05-0.3.8.0.0` },
          { text: '九、胫腓骨干双骨折', link: `${path.main}gk05-0.3.9.0.0` },
          { text: '十、踝部骨折', link: `${path.main}gk05-0.3.10.0.0` },
          { text: '十一、距骨骨折', link: `${path.main}gk05-0.3.11.0.0` },
          { text: '十二、跟骨骨折', link: `${path.main}gk05-0.3.12.0.0` },
          { text: '十三、跖骨骨折', link: `${path.main}gk05-0.3.13.0.0` },
          { text: '十四、趾骨骨折', link: `${path.main}gk05-0.3.14.0.0` },
        ],
      },
      { text: '第四节 脊柱骨折与脱位', link: `${path.main}gk05-0.4.0.0.0` },
      { text: '第五节 肋骨骨折', link: `${path.main}gk05-0.5.0.0.0` },
      { text: '第六节 感染、开放性骨折', link: `${path.main}gk05-0.6.0.0.0` },
      {
        text: '第七节 关节脱位',
        link: `${path.main}gk05-0.7.0.0.0`,
        collapsed: true,
        items: [
          { text: '一、颞颌关节脱位', link: `${path.main}gk05-0.7.1.0.0` },
          { text: '二、肩关节脱位', link: `${path.main}gk05-0.7.2.0.0` },
          { text: '三、肘关节脱位', link: `${path.main}gk05-0.7.3.0.0` },
          { text: '四、腕掌关节脱位', link: `${path.main}gk05-0.7.4.0.0` },
          { text: '五、髋关节脱位', link: `${path.main}gk05-0.7.5.0.0` },
          { text: '六、膝关节脱位', link: `${path.main}gk05-0.7.6.0.0` },
        ],
      },
    ],
  },
  {
    text: '第六章 筋骨缝损伤',
    link: `${path.main}gk06`,
    collapsed: true,
    items: [
      {
        text: '第一节 头颈部筋骨缝损伤',
        link: `${path.main}gk06-0.1.0.0.0`,
        collapsed: true,
        items: [
          { text: '一、颈背肌扭伤', link: `${path.main}gk06-0.1.1.0.0` },
          { text: '二、落枕', link: `${path.main}gk06-0.1.2.0.0` },
          { text: '三、颈椎病', link: `${path.main}gk06-0.1.3.0.0` },
        ],
      },
      {
        text: '第二节 胸腰部筋骨缝损伤',
        link: `${path.main}gk06-0.2.0.0.0`,
        collapsed: true,
        items: [
          { text: '一、胸壁挫伤', link: `${path.main}gk06-0.2.1.0.0` },
          { text: '二、急性腰扭伤', link: `${path.main}gk06-0.2.2.0.0` },
          { text: '三、劳损性腰痛', link: `${path.main}gk06-0.2.3.0.0` },
          { text: '四、腰椎肥大性脊柱炎', link: `${path.main}gk06-0.2.4.0.0` },
          { text: '五、腰椎后小关节紊乱症', link: `${path.main}gk06-0.2.5.0.0` },
          { text: '六、腰椎间盘突出症', link: `${path.main}gk06-0.2.6.0.0` },
        ],
      },
      {
        text: '第三节 上肢筋骨缝损伤',
        link: `${path.main}gk06-0.3.0.0.0`,
        collapsed: true,
        items: [
          { text: '一、肩关节周围炎', link: `${path.main}gk06-0.3.1.0.0` },
          { text: '二、网球肘', link: `${path.main}gk06-0.3.2.0.0` },
          { text: '三、腕管综合征', link: `${path.main}gk06-0.3.3.0.0` },
          { text: '四、腱鞘炎', link: `${path.main}gk06-0.3.4.0.0` },
          { text: '五、腱鞘囊肿', link: `${path.main}gk06-0.3.5.0.0` },
        ],
      },
      {
        text: '第四节 下肢筋骨缝损伤',
        link: `${path.main}gk06-0.4.0.0.0`,
        collapsed: true,
        items: [
          { text: '一、梨状肌综合征', link: `${path.main}gk06-0.4.1.0.0` },
          { text: '二、闪髋症', link: `${path.main}gk06-0.4.2.0.0` },
          { text: '三、膝关节副韧带损伤', link: `${path.main}gk06-0.4.3.0.0` },
          { text: '四、膝关节十字韧带损伤', link: `${path.main}gk06-0.4.4.0.0` },
          { text: '五、膝关节半月板损伤', link: `${path.main}gk06-0.4.5.0.0` },
          { text: '六、髌骨软化症', link: `${path.main}gk06-0.4.6.0.0` },
          { text: '七、踝关节损伤', link: `${path.main}gk06-0.4.7.0.0` },
          { text: '八、足跟痛', link: `${path.main}gk06-0.4.8.0.0` },
        ],
      },
    ],
  },
  {
    text: '第七章内伤',
    link: `${path.main}gk07`,
    collapsed: true,
    items: [
      {
        text: '第一节概论',
        link: `${path.main}gk07-0.1.0.0.0`,
        collapsed: true,
        items: [
          { text: '一、内伤的病因病机', link: `${path.main}gk07-0.1.1.0.0` },
          { text: '二、内伤的辨证诊断', link: `${path.main}gk07-0.1.2.0.0` },
          { text: '三、治疗原则', link: `${path.main}gk07-0.1.3.0.0` },
        ],
      },
      { text: '第二节　头部内伤', link: `${path.main}gk07-0.2.0.0.0` },
      { text: '第三节　胸胁部内伤', link: `${path.main}gk07-0.3.0.0.0` },
      { text: '第四节　腹部内伤', link: `${path.main}gk07-0.4.0.0.0` },
    ],
  },
  { text: '电子版录入与校对', link: `${path.main}dzb` },
];

export { sidebar as gk };
