const path = {
  main: '/gmzyjc/ok/yk/',
};

const sidebar = [
  { text: '《中医眼科学》' },
  { text: '编者与编者的话', link: `${path.main}yk00` },
  { text: '导言', link: `${path.main}daoyan` },
  {
    text: '上篇 总论',
    link: `${path.main}yk0zl01`,
    collapsed: true,
    items: [
      {
        text: '第一章 中医眼科学发展简史',
        link: `${path.main}yk0zl01-1.0.0.0.0`,
        collapsed: true,
        items: [
          { text: '萌芽时期', link: `${path.main}yk0zl01-1.1.0.0.0` },
          { text: '形成时期', link: `${path.main}yk0zl01-1.2.0.0.0` },
          { text: '发展时期', link: `${path.main}yk0zl01-1.3.0.0.0` },
          { text: '兴盛时期', link: `${path.main}yk0zl01-1.4.0.0.0` },
          { text: '衰落与复兴时期', link: `${path.main}yk0zl01-1.5.0.0.0` },
        ],
      },
      {
        text: '第二章 眼的构造与功能',
        link: `${path.main}yk0zl02`,
        collapsed: true,
        items: [
          { text: '第一节 眼的构造', link: `${path.main}yk0zl02-0.1.0.0.0` },
          { text: '第二节 神光的产生', link: `${path.main}yk0zl02-0.2.0.0.0` },
        ],
      },
      {
        text: '第三章 眼与脏腑经络的关系',
        link: `${path.main}yk0zl03`,
        collapsed: true,
        items: [
          { text: '第一节 眼与脏腑的关系', link: `${path.main}yk0zl03-0.1.0.0.0` },
          { text: '第二节 眼与经络的关系', link: `${path.main}yk0zl03-0.2.0.0.0` },
        ],
      },
      {
        text: '第四章 五轮八廓',
        link: `${path.main}yk0zl04`,
        collapsed: true,
        items: [
          { text: '第一节 五轮概要', link: `${path.main}yk0zl04-0.1.0.0.0` },
          { text: '第二节 八廓概要', link: `${path.main}yk0zl04-0.2.0.0.0` },
          { text: '第三节 五轮八廓学说在临证上的应用', link: `${path.main}yk0zl04-0.3.0.0.0` },
        ],
      },
      {
        text: '第五章 病因病机',
        link: `${path.main}yk0zl05`,
        collapsed: true,
        items: [
          { text: '第一节 病因', link: `${path.main}yk0zl05-0.1.0.0.0` },
          { text: '第二节 病机', link: `${path.main}yk0zl05-0.2.0.0.0` },
        ],
      },
      {
        text: '第六章 诊法',
        link: `${path.main}yk0zl06`,
        collapsed: true,
        items: [
          { text: '第一节 问诊', link: `${path.main}yk0zl06-0.1.0.0.0` },
          { text: '第二节 望诊', link: `${path.main}yk0zl06-0.2.0.0.0` },
          { text: '第三节 闻诊', link: `${path.main}yk0zl06-0.3.0.0.0` },
          { text: '第四节 切诊', link: `${path.main}yk0zl06-0.4.0.0.0` },
          {
            text: '第五节 常用辨证方法',
            link: `${path.main}yk0zl06-0.5.0.0.0`,
            collapsed: true,
            items: [
              { text: '一、八纲辨证', link: `${path.main}yk0zl06-0.5.1.0.0` },
              { text: '二、五轮辨证', link: `${path.main}yk0zl06-0.5.2.0.0` },
              { text: '三、八廓辨证', link: `${path.main}yk0zl06-0.5.3.0.0` },
              { text: '四、脏腑辨证', link: `${path.main}yk0zl06-0.5.4.0.0` },
              { text: '五、六经辨证', link: `${path.main}yk0zl06-0.5.5.0.0` },
              { text: '六、常见症状辨证', link: `${path.main}yk0zl06-0.5.6.0.0` },
            ],
          },
        ],
      },
      {
        text: '第七章 治则与治法',
        link: `${path.main}yk0zl07`,
        collapsed: true,
        items: [
          {
            text: '第一节 治则',
            link: `${path.main}yk0zl07-0.1.0.0.0`,
            collapsed: true,
            items: [
              { text: '一、早期治疗，防止传变', link: `${path.main}yk0zl07-0.1.1.0.0` },
              { text: '二、掌握标本缓急', link: `${path.main}yk0zl07-0.1.2.0.0` },
              { text: '三、损有余，补不足', link: `${path.main}yk0zl07-0.1.3.0.0` },
              { text: '四、因时、因地、因人制宜', link: `${path.main}yk0zl07-0.1.4.0.0` },
            ],
          },
          {
            text: '第二节 常用治法',
            link: `${path.main}yk0zl07-0.2.0.0.0`,
            collapsed: true,
            items: [
              { text: '一、内治法', link: `${path.main}yk0zl07-0.2.1.0.0` },
              { text: '二、外治法', link: `${path.main}yk0zl07-0.2.2.0.0` },
              { text: '三、常用手术疗法', link: `${path.main}yk0zl07-0.2.3.0.0` },
              { text: '四、针灸疗法', link: `${path.main}yk0zl07-0.2.4.0.0` },
            ],
          },
        ],
      },
      {
        text: '第八章 眼病的调护和预防',
        link: `${path.main}yk0zl08`,
        collapsed: true,
        items: [
          { text: '第一节 调护', link: `${path.main}yk0zl08-0.1.0.0.0` },
          { text: '第二节 预防', link: `${path.main}yk0zl08-0.2.0.0.0` },
        ],
      },
    ],
  },
  {
    text: '下篇 各论',
    link: `${path.main}yk1gl01`,
    collapsed: true,
    items: [
      {
        text: '第一章 胞睑疾患',
        link: `${path.main}yk1gl01-1.0.0.0.0`,
        collapsed: true,
        items: [
          { text: '针眼 眼丹', link: `${path.main}yk1gl01-1.1.0.0.0` },
          { text: '眼胞痰核', link: `${path.main}yk1gl01-1.2.0.0.0` },
          { text: '椒疮', link: `${path.main}yk1gl01-1.3.0.0.0` },
          { text: '粟疮', link: `${path.main}yk1gl01-1.4.0.0.0` },
          { text: '附：粟子疾', link: `${path.main}yk1gl01-1.5.0.0.0` },
          { text: '睑弦赤烂', link: `${path.main}yk1gl01-1.6.0.0.0` },
          { text: '风赤疮痍', link: `${path.main}yk1gl01-1.7.0.0.0` },
          { text: '胞肿如桃 胞虚如球', link: `${path.main}yk1gl01-1.8.0.0.0` },
          { text: '上胞下垂', link: `${path.main}yk1gl01-1.9.0.0.0` },
          { text: '倒睫拳毛', link: `${path.main}yk1gl01-1.10.0.0.0` },
          { text: '胞轮振跳', link: `${path.main}yk1gl01-1.11.0.0.0` },
          { text: '目劄', link: `${path.main}yk1gl01-1.12.0.0.0` },
        ],
      },
      {
        text: '第二章 两眦疾患',
        link: `${path.main}yk1gl02`,
        collapsed: true,
        items: [
          { text: '赤脉传睛', link: `${path.main}yk1gl02-0.1.0.0.0` },
          { text: '胬肉攀睛', link: `${path.main}yk1gl02-0.2.0.0.0` },
          {
            text: '漏睛疮 漏睛证',
            link: `${path.main}yk1gl02-0.3.0.0.0`,
            collapsed: true,
            items: [
              { text: '〔漏睛疮〕', link: `${path.main}yk1gl02-0.3.1.0.0` },
              { text: '〔漏睛证〕', link: `${path.main}yk1gl02-0.3.2.0.0` },
            ],
          },
        ],
      },
      {
        text: '第三章 白睛疾患',
        link: `${path.main}yk1gl03`,
        collapsed: true,
        items: [
          { text: '风热赤眼', link: `${path.main}yk1gl03-0.1.0.0.0` },
          { text: '天行赤眼', link: `${path.main}yk1gl03-0.2.0.0.0` },
          { text: '金疳', link: `${path.main}yk1gl03-0.3.0.0.0` },
          { text: '火疳', link: `${path.main}yk1gl03-0.4.0.0.0` },
          { text: '白涩证', link: `${path.main}yk1gl03-0.5.0.0.0` },
          { text: '白睛溢血', link: `${path.main}yk1gl03-0.6.0.0.0` },
        ],
      },
      {
        text: '第四章 黑睛疾患',
        link: `${path.main}yk1gl04`,
        collapsed: true,
        items: [
          { text: '赤膜下垂 血翳包睛', link: `${path.main}yk1gl04-0.1.0.0.0` },
          { text: '聚星障', link: `${path.main}yk1gl04-0.2.0.0.0` },
          { text: '花翳白陷', link: `${path.main}yk1gl04-0.3.0.0.0` },
          { text: '凝脂翳', link: `${path.main}yk1gl04-0.4.0.0.0` },
          { text: '黄液上冲', link: `${path.main}yk1gl04-0.5.0.0.0` },
          { text: '蟹睛证', link: `${path.main}yk1gl04-0.6.0.0.0` },
          { text: '混睛障', link: `${path.main}yk1gl04-0.7.0.0.0` },
          { text: '轮际起泡 风轮赤豆', link: `${path.main}yk1gl04-0.8.0.0.0` },
          { text: '宿翳', link: `${path.main}yk1gl04-0.9.0.0.0` },
        ],
      },
      {
        text: '第五章 瞳神疾患',
        link: `${path.main}yk1gl05`,
        collapsed: true,
        items: [
          { text: '瞳神紧小 瞳神干缺', link: `${path.main}yk1gl05-0.1.0.0.0` },
          { text: '瞳神散大', link: `${path.main}yk1gl05-0.2.0.0.0` },
          { text: '五风内障', link: `${path.main}yk1gl05-0.3.0.0.0` },
          {
            text: '视瞻昏渺 青盲',
            link: `${path.main}yk1gl05-0.4.0.0.0`,
            collapsed: true,
            items: [{ text: '附：小儿青盲', link: `${path.main}yk1gl05-0.4.1.0.0` }],
          },
          { text: '暴盲', link: `${path.main}yk1gl05-0.5.0.0.0` },
          {
            text: '如银内障',
            link: `${path.main}yk1gl05-0.6.0.0.0`,
            collapsed: true,
            items: [
              { text: '附一：如银内障针拨术', link: `${path.main}yk1gl05-0.6.1.0.0` },
              { text: '附二：胎患内障', link: `${path.main}yk1gl05-0.6.2.0.0` },
              { text: '附三：惊震内障', link: `${path.main}yk1gl05-0.6.3.0.0` },
              { text: '附四：五风变内障', link: `${path.main}yk1gl05-0.6.4.0.0` },
              { text: '附五：冰翳内障', link: `${path.main}yk1gl05-0.6.5.0.0` },
            ],
          },
          { text: '视惑证', link: `${path.main}yk1gl05-0.7.0.0.0` },
          { text: '云雾移睛', link: `${path.main}yk1gl05-0.8.0.0.0` },
          { text: '血灌瞳神', link: `${path.main}yk1gl05-0.9.0.0.0` },
          { text: '肝虚雀目 高风雀目', link: `${path.main}yk1gl05-0.10.0.0.0` },
          { text: '视物易色', link: `${path.main}yk1gl05-0.11.0.0.0` },
          { text: '能近怯远  能远怯近', link: `${path.main}yk1gl05-0.12.0.0.0` },
        ],
      },
      {
        text: '第六章 其他疾患',
        link: `${path.main}yk1gl06`,
        collapsed: true,
        items: [
          { text: '流泪证', link: `${path.main}yk1gl06-0.1.0.0.0` },
          { text: '麻毒攻目', link: `${path.main}yk1gl06-0.2.0.0.0` },
          { text: '疳疾上目', link: `${path.main}yk1gl06-0.3.0.0.0` },
          {
            text: '侧目斜视',
            link: `${path.main}yk1gl06-0.4.0.0.0`,
            collapsed: true,
            items: [{ text: '附：口眼㖞斜', link: `${path.main}yk1gl06-0.4.1.0.0` }],
          },
          { text: '突起睛高', link: `${path.main}yk1gl06-0.5.0.0.0` },
          { text: '初生儿目肿不开证', link: `${path.main}yk1gl06-0.6.0.0.0` },
          { text: '妇人经胎产期目病', link: `${path.main}yk1gl06-0.7.0.0.0` },
          { text: '目痒', link: `${path.main}yk1gl06-0.8.0.0.0` },
        ],
      },
      {
        text: '第七章 外伤疾患',
        link: `${path.main}yk1gl07`,
        collapsed: true,
        items: [
          { text: '异物入目', link: `${path.main}yk1gl07-0.1.0.0.0` },
          { text: '撞击伤目', link: `${path.main}yk1gl07-0.2.0.0.0` },
          { text: '真睛破损', link: `${path.main}yk1gl07-0.3.0.0.0` },
          { text: '强光伤目', link: `${path.main}yk1gl07-0.4.0.0.0` },
          { text: '酸碱烧伤', link: `${path.main}yk1gl07-0.5.0.0.0` },
        ],
      },
      {
        text: '附篇',
        link: `${path.main}yk2fp`,
        collapsed: true,
        items: [
          { text: '一、识病辨证详明金玉赋', link: `${path.main}yk2fp-0.0.1.0.0` },
          { text: '二、视力检查法', link: `${path.main}yk2fp-0.0.2.0.0` },
          { text: '三、视野检查法', link: `${path.main}yk2fp-0.0.3.0.0` },
          { text: '四、色觉检查法', link: `${path.main}yk2fp-0.0.4.0.0` },
          { text: '五、眼压检查法', link: `${path.main}yk2fp-0.0.5.0.0` },
          { text: '六、裂隙灯显微镜检查法', link: `${path.main}yk2fp-0.0.6.0.0` },
          { text: '七、内眼检查法', link: `${path.main}yk2fp-0.0.7.0.0` },
          { text: '八、眼科病案的内容与书写要求', link: `${path.main}yk2fp-0.0.8.0.0` },
          { text: '九、眼科常用药物', link: `${path.main}yk2fp-0.0.9.0.0` },
        ],
      },
    ],
  },
  { text: '常见证治方剂', link: `${path.main}yk3cjfj` },
  { text: '电子版录入与校对', link: `${path.main}dzb` },
];

export { sidebar as yk };
