const path = {
  main: '/gmzyjc/ok/fk/',
};

const sidebar = [
  { text: '编者与编者的话', link: `${path.main}fk00` },
  { text: '导言', link: `${path.main}daoyan` },
  {
    text: '总论',
    link: `${path.main}fk0zl00`,
    collapsed: true,
    items: [
      {
        text: '第一章 中医妇科学的发展概况',
        link: `${path.main}fk0zl01`,
        collapsed: true,
        items: [
          { text: '第一节 中医妇科学的发展史', link: `${path.main}fk0zl01-0.1.0.0.0` },
          { text: '第二节 历代妇产科主要著作简介', link: `${path.main}fk0zl01-0.2.0.0.0` },
        ],
      },
      {
        text: '第二章 妇女的生理特点',
        link: `${path.main}fk0zl02`,
        collapsed: true,
        items: [
          { text: '第一节 女性特有的器官及其生理作用', link: `${path.main}fk0zl02-0.1.0.0.0` },
          { text: '第二节 月经的生理', link: `${path.main}fk0zl02-0.2.0.0.0` },
          { text: '第三节 带下的生理', link: `${path.main}fk0zl02-0.3.0.0.0` },
          { text: '第四节 妊娠与产育的生理', link: `${path.main}fk0zl02-0.4.0.0.0` },
          { text: '第五节 祖国医学中的优生学思想', link: `${path.main}fk0zl02-0.5.0.0.0` },
        ],
      },
      {
        text: '第三章妇女的病理特点',
        link: `${path.main}fk0zl03`,
        collapsed: true,
        items: [
          { text: '第一节病因', link: `${path.main}fk0zl03-0.1.0.0.0` },
          { text: '第二节病机', link: `${path.main}fk0zl03-0.2.0.0.0` },
        ],
      },
      {
        text: '第四章妇科病的诊断要点',
        link: `${path.main}fk0zl04`,
        collapsed: true,
        items: [
          { text: '第一节四诊要点', link: `${path.main}fk0zl04-0.1.0.0.0` },
          { text: '第二节辨证要点', link: `${path.main}fk0zl04-0.2.0.0.0` },
        ],
      },
      {
        text: '第五章妇科病的治法概要',
        link: `${path.main}fk0zl05`,
        collapsed: true,
        items: [
          { text: '第一节妇科常用治法', link: `${path.main}fk0zl05-0.1.0.0.0` },
          { text: '第二节妇科方药运用举例', link: `${path.main}fk0zl05-0.2.0.0.0` },
          { text: '第三节中草药节育研究概况', link: `${path.main}fk0zl05-0.3.0.0.0` },
        ],
      },
      {
        text: '第六章 妇女摄生与保健',
        link: `${path.main}fk0zl06`,
        collapsed: true,
        items: [
          { text: '第一节 经期摄生', link: `${path.main}fk0zl06-0.1.0.0.0` },
          { text: '第二节 孕期摄生', link: `${path.main}fk0zl06-0.2.0.0.0` },
          { text: '第三节 产褥期摄生', link: `${path.main}fk0zl06-0.3.0.0.0` },
          { text: '第四节 哺乳期摄生', link: `${path.main}fk0zl06-0.4.0.0.0` },
          { text: '第五节 绝经期摄生', link: `${path.main}fk0zl06-0.5.0.0.0` },
        ],
      },
      {
        text: '第七章 妇科学的学习方法',
        link: `${path.main}fk0zl07`,
        collapsed: true,
        items: [
          { text: '第一节 掌握基础理论是学好中医妇科的前提', link: `${path.main}fk0zl07-0.1.0.0.0` },
          { text: '第二节 临床实践是学习中医妇科学的重要途径', link: `${path.main}fk0zl07-0.2.0.0.0` },
          { text: '第三节 熟读泛览是妇科入门的阶梯', link: `${path.main}fk0zl07-0.3.0.0.0` },
        ],
      },
    ],
  },
  {
    text: '各论',
    link: `${path.main}fkgl01`,
    collapsed: true,
    items: [
      {
        text: '第一章 月经病证门',
        link: `${path.main}fkgl01-1.0.0.0.0`,
        collapsed: true,
        items: [
          { text: '月经先期', link: `${path.main}fkgl01-1.1.0.0.0` },
          { text: '月经后期', link: `${path.main}fkgl01-1.2.0.0.0` },
          { text: '月经先后无定期', link: `${path.main}fkgl01-1.3.0.0.0` },
          { text: '月经过多', link: `${path.main}fkgl01-1.4.0.0.0` },
          { text: '月经过少', link: `${path.main}fkgl01-1.5.0.0.0` },
          { text: '经期延长', link: `${path.main}fkgl01-1.6.0.0.0` },
          { text: '痛经', link: `${path.main}fkgl01-1.7.0.0.0` },
          { text: '经间期出血', link: `${path.main}fkgl01-1.8.0.0.0` },
          { text: '闭经', link: `${path.main}fkgl01-1.9.0.0.0` },
          { text: '崩漏', link: `${path.main}fkgl01-1.10.0.0.0` },
          { text: '逆经', link: `${path.main}fkgl01-1.11.0.0.0` },
          { text: '经行乳房胀痛', link: `${path.main}fkgl01-1.12.0.0.0` },
          { text: '经行发热', link: `${path.main}fkgl01-1.13.0.0.0` },
          { text: '经行头痛', link: `${path.main}fkgl01-1.14.0.0.0` },
          { text: '经行身痛', link: `${path.main}fkgl01-1.15.0.0.0` },
          { text: '经行泄泻', link: `${path.main}fkgl01-1.16.0.0.0` },
          { text: '经行口糜', link: `${path.main}fkgl01-1.17.0.0.0` },
          { text: '经行风疹块', link: `${path.main}fkgl01-1.18.0.0.0` },
          { text: '经行眩晕', link: `${path.main}fkgl01-1.19.0.0.0` },
          { text: '经行浮肿', link: `${path.main}fkgl01-1.20.0.0.0` },
          { text: '经行情志异常', link: `${path.main}fkgl01-1.21.0.0.0` },
          { text: '绝经前后诸证', link: `${path.main}fkgl01-1.22.0.0.0` },
          { text: '老年经断复行', link: `${path.main}fkgl01-1.23.0.0.0` },
        ],
      },
      {
        text: '第二章 带下病证门',
        link: `${path.main}fkgl02`,
        collapsed: true,
        items: [
          { text: '白带', link: `${path.main}fkgl02-0.1.0.0.0` },
          { text: '黄带', link: `${path.main}fkgl02-0.2.0.0.0` },
          { text: '赤带', link: `${path.main}fkgl02-0.3.0.0.0` },
          { text: '赤白带', link: `${path.main}fkgl02-0.4.0.0.0` },
          { text: '五色带', link: `${path.main}fkgl02-0.5.0.0.0` },
        ],
      },
      {
        text: '第三章妊娠病证门',
        link: `${path.main}fkgl03`,
        collapsed: true,
        items: [
          { text: '妊娠恶阻', link: `${path.main}fkgl03-0.1.0.0.0` },
          { text: '胞阻', link: `${path.main}fkgl03-0.2.0.0.0` },
          { text: '异位妊娠', link: `${path.main}fkgl03-0.3.0.0.0` },
          { text: '流产', link: `${path.main}fkgl03-0.4.0.0.0` },
          { text: '胎萎', link: `${path.main}fkgl03-0.5.0.0.0` },
          { text: '子烦', link: `${path.main}fkgl03-0.6.0.0.0` },
          { text: '子肿', link: `${path.main}fkgl03-0.7.0.0.0` },
          { text: '子晕', link: `${path.main}fkgl03-0.8.0.0.0` },
          { text: '子痫', link: `${path.main}fkgl03-0.9.0.0.0` },
          { text: '子悬', link: `${path.main}fkgl03-0.10.0.0.0` },
          { text: '子瘖', link: `${path.main}fkgl03-0.11.0.0.0` },
          { text: '子嗽', link: `${path.main}fkgl03-0.12.0.0.0` },
          { text: '子淋', link: `${path.main}fkgl03-0.13.0.0.0` },
          { text: '转胞', link: `${path.main}fkgl03-0.14.0.0.0` },
        ],
      },
      {
        text: '第四章 子嗣门',
        link: `${path.main}fkgl04`,
        collapsed: true,
        items: [{ text: '不孕证', link: `${path.main}fkgl04-0.1.0.0.0` }],
      },
      {
        text: '第五章 产后病证门',
        link: `${path.main}fkgl05`,
        collapsed: true,
        items: [
          { text: '胞衣不下', link: `${path.main}fkgl05-0.1.0.0.0` },
          { text: '产后血晕', link: `${path.main}fkgl05-0.2.0.0.0` },
          { text: '产后痉证', link: `${path.main}fkgl05-0.3.0.0.0` },
          { text: '产后腹痛', link: `${path.main}fkgl05-0.4.0.0.0` },
          { text: '恶露不下', link: `${path.main}fkgl05-0.5.0.0.0` },
          { text: '恶露不绝', link: `${path.main}fkgl05-0.6.0.0.0` },
          { text: '产后发热', link: `${path.main}fkgl05-0.7.0.0.0` },
          { text: '产后身痛', link: `${path.main}fkgl05-0.8.0.0.0` },
          { text: '产后排尿异常', link: `${path.main}fkgl05-0.9.0.0.0` },
          { text: '产后大便难', link: `${path.main}fkgl05-0.10.0.0.0` },
          { text: '产后自汗、盗汗', link: `${path.main}fkgl05-0.11.0.0.0` },
          { text: '缺乳', link: `${path.main}fkgl05-0.12.0.0.0` },
          { text: '产后乳汁自出', link: `${path.main}fkgl05-0.13.0.0.0` },
        ],
      },
      {
        text: '第六章 杂病证门',
        link: `${path.main}fkgl06`,
        collapsed: true,
        items: [
          { text: '癥瘕', link: `${path.main}fkgl06-0.1.0.0.0` },
          { text: '脏躁', link: `${path.main}fkgl06-0.2.0.0.0` },
          { text: '阴挺', link: `${path.main}fkgl06-0.3.0.0.0` },
          { text: '阴痒', link: `${path.main}fkgl06-0.4.0.0.0` },
          { text: '阴吹', link: `${path.main}fkgl06-0.5.0.0.0` },
        ],
      },
    ],
  },
  { text: '常见证治方剂索引', link: `${path.main}fkgl07fjsy` },
  { text: '电子版录入与校对', link: `${path.main}dzb` },
];

export { sidebar as fk };
