const path = {
  main: '/gmzyjc/ok/gmrw/',
};

const sidebar = [
  { text: '《光明人物》' },
  {
    text: '传略',
    collapsed: true,
    items: [
      { text: '光明中医函授大学顾问丁光迪传略', link: `${path.main}丁光迪` },
      { text: '光明中医函授大学顾问万友生传略', link: `${path.main}万友生` },
      { text: '光明中医函授大学顾问于己百传略', link: `${path.main}于己百` },
      { text: '光明中医函授大学顾问何世英传略', link: `${path.main}何世英` },
      { text: '光明中医函授大学顾问何任传略', link: `${path.main}何任` },
      { text: '光明中医函授大学顾问何时希传略', link: `${path.main}何时希` },
      { text: '光明中医函授大学顾问余瀛鳌传略', link: `${path.main}余瀛鳌` },
      { text: '光明中医函授大学顾问俞长荣传略', link: `${path.main}俞长荣` },
      { text: '光明中医函授大学顾问傅宗翰传略', link: `${path.main}傅宗翰` },
      { text: '光明中医函授大学顾问凌一揆传略', link: `${path.main}凌一揆` },
      { text: '光明中医函授大学顾问刘亚娴传略', link: `${path.main}刘亚娴` },
      { text: '光明中医函授大学顾问刘冠军传略', link: `${path.main}刘冠军` },
      { text: '光明中医函授大学顾问刘弼臣传略', link: `${path.main}刘弼臣` },
      { text: '刘渡舟-《伤寒论讲解》主编', link: `${path.main}刘渡舟` },
      { text: '光明中医函授大学顾问刘炳凡传略', link: `${path.main}刘炳凡` },
      { text: '光明中医函授大学顾问刘长林传略', link: `${path.main}刘长林` },
      { text: '光明中医函授大学顾问吕仁和传略', link: `${path.main}吕仁和` },
      { text: '中医司令吕炳奎', link: `${path.main}吕炳奎` },
      { text: '吴大真-《本草备要讲解》编者', link: `${path.main}吴大真` },
      { text: '光明中医函授大学顾问周仲英传略', link: `${path.main}周仲英` },
      { text: '光明中医函授大学顾问周信有传略', link: `${path.main}周信有` },
      { text: '光明中医函授大学副校长周凤梧传略', link: `${path.main}周凤梧` },
      { text: '光明中医函授大学顾问哈荔田传略', link: `${path.main}哈荔田` },
      { text: '光明中医函授大学顾问孙光荣传略', link: `${path.main}孙光荣` },
      { text: '光明中医函授大学顾问尚志钧传略', link: `${path.main}尚志钧` },
      { text: '崔月犁传略', link: `${path.main}崔月犁` },
      { text: '光明中医函授大学副校长巫君玉传略', link: `${path.main}巫君玉` },
      { text: '干祖望-《中医喉科学》编者', link: `${path.main}干祖望` },
      { text: '光明中医函授大学顾问张世臣传略', link: `${path.main}张世臣` },
      { text: '光明中医函授大学副校长张协和传略', link: `${path.main}张协和` },
      { text: '光明中医函授大学顾问张奇文传略', link: `${path.main}张奇文` },
      { text: '光明中医函授大学顾问张学文传略', link: `${path.main}张学文` },
      { text: '光明中医函授大学顾问张海峰传略', link: `${path.main}张海峰` },
      { text: '光明中医函授大学顾问张缙传略', link: `${path.main}张缙` },
      { text: '光明中医函授大学顾问张赞臣传略', link: `${path.main}张赞臣` },
      { text: '光明中医函授大学顾问张镜人传略', link: `${path.main}张镜人` },
      { text: '光明中医函授大学顾问彭静山传略', link: `${path.main}彭静山` },
      { text: '光明中医函授大学顾问朱良春传略', link: `${path.main}朱良春` },
      { text: '光明中医函授大学顾问李今庸传略', link: `${path.main}李今庸` },
      { text: '光明中医函授大学顾问李仲愚传略', link: `${path.main}李仲愚` },
      { text: '光明中医函授大学顾问李培生传略', link: `${path.main}李培生` },
      { text: '光明中医函授大学顾问李振华', link: `${path.main}李振华` },
      { text: '光明中医函授大学顾问李玉奇传略', link: `${path.main}李玉奇` },
      { text: '光明中医函授大学顾问李聪甫传略', link: `${path.main}李聪甫` },
      { text: '光明中医函授大学顾问李衡友传略', link: `${path.main}李衡友` },
      { text: '光明教材编者樊正伦', link: `${path.main}樊正伦` },
      { text: '光明中医函授大学顾问江育仁传略', link: `${path.main}江育仁` },
      { text: '光明中医函授大学顾问潘澄濂传略', link: `${path.main}潘澄濂` },
      { text: '光明中医函授大学顾问焦树德传略', link: `${path.main}焦树德` },
      { text: '光明中医函授大学副校长王伯岳传略', link: `${path.main}王伯岳` },
      { text: '光明中医函授大学顾问王克勤传略', link: `${path.main}王克勤` },
      { text: '光明中医函授大学校长王恩厚传略', link: `${path.main}王恩厚` },
      { text: '光明中医函授大学顾问王永炎传略', link: `${path.main}王永炎` },
      { text: '光明中医函授大学副校长王绵之传略', link: `${path.main}王绵之` },
      { text: '光明中医函授大学顾问王鸿士传略', link: `${path.main}王鸿士` },
      { text: '光明中医函授大学顾问盛亦如传略', link: `${path.main}盛亦如` },
      { text: '光明中医函授大学顾问程莘农传略', link: `${path.main}程莘农` },
      { text: '光明中医函授大学顾问罗元恺传略', link: `${path.main}罗元恺` },
      { text: '光明中医函授大学顾问茹古香传略', link: `${path.main}茹古香` },
      { text: '光明中医函授大学顾问董建华传略', link: `${path.main}董建华` },
      { text: '光明中医函授大学顾问蔡友敬传略', link: `${path.main}蔡友敬` },
      { text: '光明中医函授大学顾问袁家玑传略', link: `${path.main}袁家玑` },
      { text: '光明中医函授大学顾问裘沛然传略', link: `${path.main}裘沛然` },
      { text: '光明中医函授大学顾问谢海洲传略', link: `${path.main}谢海洲` },
      { text: '光明教材编者赵尚华-《中医外科学》主编', link: `${path.main}赵尚华` },
      { text: '光明中医函授大学顾问赵绍琴传略', link: `${path.main}赵绍琴` },
      { text: '光明中医函授大学顾问路志正传略', link: `${path.main}路志正` },
      { text: '光明中医函授大学顾问郑金生传略', link: `${path.main}郑金生` },
      { text: '光明中医函授大学顾问郭霭春传略', link: `${path.main}郭霭春` },
      { text: '光明中医函授大学顾问金世元传略', link: `${path.main}金世元` },
      { text: '光明中医函授大学顾问金树滋传略', link: `${path.main}金树滋` },
      { text: '光明中医函授大学顾问钟一棠传略', link: `${path.main}钟一棠` },
      { text: '光明教材编者钱超尘', link: `${path.main}钱超尘` },
      { text: '光明中医函授大学顾问陶广正传略', link: `${path.main}陶广正` },
      { text: '光明中医函授大学顾问韩百灵传略', link: `${path.main}韩百灵` },
      { text: '光明中医函授大学顾问马有度传略', link: `${path.main}马有度` },
      { text: '光明中医函授大学顾问高荣林传略', link: `${path.main}高荣林` },
    ],
  },
  {
    text: '毕业生名单',
    collapsed: true,
    items: [
      { text: '85级毕业生名单（1）', link: `${path.main}gmrw-85-1` },
      { text: '85级毕业生名单（2）', link: `${path.main}gmrw-85-2` },
      { text: '85级毕业生名单（3）', link: `${path.main}gmrw-85-3` },
      { text: '85级毕业生名单（4）', link: `${path.main}gmrw-85-4` },
      { text: '85级毕业生名单（5）', link: `${path.main}gmrw-85-5` },
      { text: '86级毕业生名单', link: `${path.main}gmrw-86` },
      { text: '87、88级毕业生名单', link: `${path.main}gmrw-87-88` },
      { text: '89级毕业生名单', link: `${path.main}gmrw-89` },
      { text: '90-93级毕业生名单', link: `${path.main}gmrw-90-93` },
    ],
  },
];

export { sidebar as gmrw };
