const path = {
  main: '/gmzyjc/ok/gbshl/',
};

const sidebar = [
  { text: '《桂本伤寒论》' },
  { text: '桂林古本《伤寒杂病论》简介', link: `${path.main}gbshl-1-0` },
  { text: '张机序', link: `${path.main}gbshl-2-1` },
  { text: '桂林左德序', link: `${path.main}gbshl-2-2` },
  { text: '平脉法第一', link: `${path.main}gbshl-3-01` },
  { text: '平脉法第二', link: `${path.main}gbshl-3-02` },
  { text: '六气主客第三', link: `${path.main}gbshl-3-03` },
  { text: '伤寒例第四', link: `${path.main}gbshl-3-04` },
  { text: '杂病例第五', link: `${path.main}gbshl-3-05` },
  { text: '温病脉证并治第六', link: `${path.main}gbshl-3-06` },
  { text: '伤暑脉证并治第七', link: `${path.main}gbshl-3-07` },
  { text: '热病脉证并治第八', link: `${path.main}gbshl-3-08` },
  { text: '湿病脉证并治第九', link: `${path.main}gbshl-3-09` },
  { text: '伤燥病脉证并治第十', link: `${path.main}gbshl-3-10` },
  { text: '伤风病脉证并治第十一', link: `${path.main}gbshl-3-11` },
  { text: '寒病脉证并治第十二', link: `${path.main}gbshl-3-12` },
  { text: '辨太阳病脉证并治上', link: `${path.main}gbshl-3-13` },
  { text: '辨太阳病脉证并治中', link: `${path.main}gbshl-3-14` },
  { text: '辨太阳病脉证并治下', link: `${path.main}gbshl-3-15` },
  { text: '辨阳明病脉证并治', link: `${path.main}gbshl-3-16` },
  { text: '辨少阳病脉证并治', link: `${path.main}gbshl-3-17` },
  { text: '辨太阴病脉证并治', link: `${path.main}gbshl-3-18` },
  { text: '辨少阴病脉证并治', link: `${path.main}gbshl-3-19` },
  { text: '辨厥阴病脉证并治', link: `${path.main}gbshl-3-20` },
  { text: '辨霍乱吐利病脉证并治', link: `${path.main}gbshl-3-21` },
  { text: '辨痉阴阳易差后病脉证并治', link: `${path.main}gbshl-3-22` },
  { text: '辨百合狐惑阴阳毒病脉证并治', link: `${path.main}gbshl-3-23` },
  { text: '辨疟病脉证并治', link: `${path.main}gbshl-3-24` },
  { text: '辨血痹虚劳病脉证并治', link: `${path.main}gbshl-3-25` },
  { text: '辨咳嗽水饮黄汗历节病脉证并治', link: `${path.main}gbshl-3-26` },
  { text: '辨瘀血吐衄下血疮痈病脉证并治', link: `${path.main}gbshl-3-27` },
  { text: '辨胸痹病脉证并治', link: `${path.main}gbshl-3-28` },
  { text: '辨妇人各病脉证并治', link: `${path.main}gbshl-3-29` },
  { text: '附：历代衡量与市秤对照表', link: `${path.main}gbshl-3-30` },
];

export { sidebar as gbshl };
