const path = {
  main: '/gmzyjc/ok/lk/',
};

const sidebar = [
  { text: '《李可疑难病经验》' },
  { text: '编者与序', link: `${path.main}lk00` },
  { text: '破格救心汤救治心衰实录', link: `${path.main}lk01` },
  { text: '肺心病急性感染', link: `${path.main}lk02` },
  { text: '风心病合并冠心病', link: `${path.main}lk03` },
  { text: '肺结核合并肺心病(戴阳危证)', link: `${path.main}lk04` },
  { text: '特发性肺间质纤维化医案二则', link: `${path.main}lk05` },
  { text: '中风七则', link: `${path.main}lk06` },
  { text: '急性结核性胸膜炎重症', link: `${path.main}lk07` },
  { text: '结核性心包炎、心包积液', link: `${path.main}lk08` },
  { text: '真热假寒大实有羸状', link: `${path.main}lk09` },
  { text: '三消重症', link: `${path.main}lk10` },
  { text: '虚寒型糖尿病', link: `${path.main}lk11` },
  { text: '糖尿病火不生土', link: `${path.main}lk12` },
  { text: '重症结核性腹膜炎合并胆囊炎', link: `${path.main}lk13` },
  { text: '血栓闭塞性脉管炎同病异治', link: `${path.main}lk14` },
  { text: '小儿重危急症医案', link: `${path.main}lk15` },
  { text: '妇科重危急症、疑难病医案', link: `${path.main}lk16` },
  { text: '外科急腹症医案十则', link: `${path.main}lk17` },
  { text: '危重痢疾六则', link: `${path.main}lk18` },
  { text: '泌尿系统疾患七则', link: `${path.main}lk19` },
  { text: '肝病五则', link: `${path.main}lk20` },
  { text: '发热待诊', link: `${path.main}lk21` },
  { text: '直中少阴', link: `${path.main}lk22` },
  { text: '阴盛格阳', link: `${path.main}lk23` },
  { text: '内伤发热', link: `${path.main}lk24` },
  { text: '煤气中毒性精神病', link: `${path.main}lk25` },
  { text: '青年期精神分裂症', link: `${path.main}lk26` },
  { text: '脑外伤性精神病', link: `${path.main}lk27` },
  { text: '五十年奔豚兼脑鸣', link: `${path.main}lk28` },
  { text: '重症呃逆', link: `${path.main}lk29` },
  { text: '表症误攻变症', link: `${path.main}lk30` },
  { text: '正气复则邪从热化例', link: `${path.main}lk31` },
  { text: '阳虚型红斑狼疮一例治验', link: `${path.main}lk32` },
  { text: '风湿热痹二则', link: `${path.main}lk33` },
  { text: '类风湿性关节炎合并硬皮病', link: `${path.main}lk34` },
  { text: '脚气四则', link: `${path.main}lk35` },
  { text: '痔漏肿痛', link: `${path.main}lk36` },
  { text: '颈椎增生症五则', link: `${path.main}lk37` },
  { text: '足跟痛(跟骨骨刺)', link: `${path.main}lk38` },
  { text: '肩凝重症', link: `${path.main}lk39` },
  { text: '五行辨证偶得五则', link: `${path.main}lk40` },
  { text: '老年荡漾震颤症', link: `${path.main}lk41` },
  { text: '身瞤动症', link: `${path.main}lk42` },
  { text: '足心发热怪症', link: `${path.main}lk43` },
  { text: '头痛三则', link: `${path.main}lk44` },
  { text: '膝关节积液的四种治法', link: `${path.main}lk45` },
  { text: '少腹鼓凸症', link: `${path.main}lk46` },
  { text: '目疾八则', link: `${path.main}lk47` },
  { text: '耳病四则', link: `${path.main}lk48` },
  { text: '鼻病五则', link: `${path.main}lk49` },
  { text: '口舌齿咽喉病十四则', link: `${path.main}lk50` },
  { text: '肺结核临证得失录', link: `${path.main}lk51` },
  { text: '乌蛇荣皮汤皮科治验录', link: `${path.main}lk52` },
  { text: '肿瘤临证初探', link: `${path.main}lk53` },
  { text: '温氏奔豚汤治验录', link: `${path.main}lk54` },
  { text: '培元固本散治诸虚百损', link: `${path.main}lk55` },
  { text: '恢复仲景用药特色，攻克世界医学难题', link: `${path.main}lk56` },
];

export { sidebar as lk };
