const path = {
  main: '/gmzyjc/ok/bc/',
};

const sidebar = [
  { text: '《本草备要讲解》' },
  { text: '编者', link: `${path.main}bc00.0` },
  { text: '导言', link: `${path.main}daoyan` },
  { text: '编者的话', link: `${path.main}bc00.0-1.0.0.0.0` },
  { text: '本草备要序', link: `${path.main}bc0001` },
  { text: '增补本草备要原序', link: `${path.main}bc0002` },
  { text: '本草备要凡例', link: `${path.main}bc0003` },
  {
    text: '药性总义',
    link: `${path.main}bc00.1`,
    collapsed: true,
    items: [
      { text: '〔原文〕', link: `${path.main}bc00.1-0.1.0.0.0` },
      {
        text: '〖讲解〗',
        link: `${path.main}bc00.1-0.2.0.0.0`,
        collapsed: true,
        items: [
          { text: '一、药性：', link: `${path.main}bc00.1-0.2.1.0.0` },
          { text: '二、配伍：', link: `${path.main}bc00.1-0.2.2.0.0` },
          { text: '三、禁忌：', link: `${path.main}bc00.1-0.2.3.0.0` },
          { text: '四、炮制：', link: `${path.main}bc00.1-0.2.4.0.0` },
          { text: '五、用量：', link: `${path.main}bc00.1-0.2.5.0.0` },
        ],
      },
    ],
  },
  {
    text: '各 论',
    link: `${path.main}bc01`,
    collapsed: true,
    items: [
      {
        text: '第一章解表药',
        link: `${path.main}bc01-1.0.0.0.0`,
        collapsed: true,
        items: [
          {
            text: '第一节辛温解表药',
            link: `${path.main}bc01-1.1.0.0.0`,
            collapsed: true,
            items: [
              { text: '麻黄', link: `${path.main}bc01-1.1.1.0.0` },
              { text: '桂枝', link: `${path.main}bc01-1.1.2.0.0` },
              { text: '紫苏', link: `${path.main}bc01-1.1.3.0.0` },
              { text: '荆芥', link: `${path.main}bc01-1.1.4.0.0` },
              { text: '防风', link: `${path.main}bc01-1.1.5.0.0` },
              { text: '羌活', link: `${path.main}bc01-1.1.6.0.0` },
              { text: '白芷', link: `${path.main}bc01-1.1.7.0.0` },
              { text: '藁本', link: `${path.main}bc01-1.1.8.0.0` },
              { text: '细辛', link: `${path.main}bc01-1.1.9.0.0` },
              { text: '辛夷', link: `${path.main}bc01-1.1.10.0.0` },
              { text: '苍耳子', link: `${path.main}bc01-1.1.11.0.0` },
              { text: '香薷', link: `${path.main}bc01-1.1.12.0.0` },
              { text: '生姜', link: `${path.main}bc01-1.1.13.0.0` },
              { text: '葱白', link: `${path.main}bc01-1.1.14.0.0` },
              { text: '胡荽', link: `${path.main}bc01-1.1.15.0.0` },
              { text: '赤柽柳', link: `${path.main}bc01-1.1.16.0.0` },
              { text: '鸡苏', link: `${path.main}bc01-1.1.17.0.0` },
            ],
          },
          {
            text: '第二节辛凉解表药',
            link: `${path.main}bc01-1.2.0.0.0`,
            collapsed: true,
            items: [
              { text: '薄荷', link: `${path.main}bc01-1.2.1.0.0` },
              { text: '牛蒡子', link: `${path.main}bc01-1.2.2.0.0` },
              { text: '桑叶', link: `${path.main}bc01-1.2.3.0.0` },
              { text: '甘菊花', link: `${path.main}bc01-1.2.4.0.0` },
              { text: '蝉蜕', link: `${path.main}bc01-1.2.5.0.0` },
              { text: '淡豆豉', link: `${path.main}bc01-1.2.6.0.0` },
              { text: '蔓荆子', link: `${path.main}bc01-1.2.7.0.0` },
              { text: '葛根', link: `${path.main}bc01-1.2.8.0.0` },
              { text: '柴胡', link: `${path.main}bc01-1.2.9.0.0` },
              { text: '升麻', link: `${path.main}bc01-1.2.10.0.0` },
              { text: '浮萍', link: `${path.main}bc01-1.2.11.0.0` },
              { text: '木贼', link: `${path.main}bc01-1.2.12.0.0` },
              { text: '小结', link: `${path.main}bc01-1.3.0.0.0` },
            ],
          },
        ],
      },
      {
        text: '第二章 泻下药',
        link: `${path.main}bc02`,
        collapsed: true,
        items: [
          {
            text: '第一节攻下药',
            link: `${path.main}bc02-0.1.0.0.0`,
            collapsed: true,
            items: [
              { text: '大黄', link: `${path.main}bc02-0.1.1.0.0` },
              { text: '朴硝 芒硝 元明粉', link: `${path.main}bc02-0.1.2.0.0` },
              { text: '芦荟', link: `${path.main}bc02-0.1.3.0.0` },
            ],
          },
          {
            text: '第二节润下药',
            link: `${path.main}bc02-0.2.0.0.0`,
            collapsed: true,
            items: [
              { text: '大麻仁', link: `${path.main}bc02-0.2.1.0.0` },
              { text: '郁李仁', link: `${path.main}bc02-0.2.2.0.0` },
              { text: '海松子', link: `${path.main}bc02-0.2.3.0.0` },
              { text: '蜂蜜', link: `${path.main}bc02-0.2.4.0.0` },
              { text: '蓖麻子', link: `${path.main}bc02-0.2.5.0.0` },
            ],
          },
          {
            text: '第三节峻下逐水药',
            link: `${path.main}bc02-0.3.0.0.0`,
            collapsed: true,
            items: [
              { text: '甘遂', link: `${path.main}bc02-0.3.1.0.0` },
              { text: '大戟', link: `${path.main}bc02-0.3.2.0.0` },
              { text: '芫花', link: `${path.main}bc02-0.3.3.0.0` },
              { text: '荛花', link: `${path.main}bc02-0.3.4.0.0` },
              { text: '巴豆', link: `${path.main}bc02-0.3.5.0.0` },
              { text: '牵牛子', link: `${path.main}bc02-0.3.6.0.0` },
              { text: '商陆', link: `${path.main}bc02-0.3.7.0.0` },
              { text: '续随子', link: `${path.main}bc02-0.3.8.0.0` },
              { text: '泽漆', link: `${path.main}bc02-0.3.9.0.0` },
            ],
          },
          { text: '小结', link: `${path.main}bc02-0.4.0.0.0` },
        ],
      },
      {
        text: '第三章清热药',
        link: `${path.main}bc03`,
        collapsed: true,
        items: [
          {
            text: '第一节清热泻火药',
            link: `${path.main}bc03-0.1.0.0.0`,
            collapsed: true,
            items: [
              { text: '石膏', link: `${path.main}bc03-0.1.1.0.0` },
              { text: '知母', link: `${path.main}bc03-0.1.2.0.0` },
              { text: '桅子', link: `${path.main}bc03-0.1.3.0.0` },
              { text: '芦根', link: `${path.main}bc03-0.1.4.0.0` },
              { text: '天花粉', link: `${path.main}bc03-0.1.5.0.0` },
              { text: '竹叶', link: `${path.main}bc03-0.1.6.0.0` },
              { text: '夏枯草', link: `${path.main}bc03-0.1.7.0.0` },
              { text: '决明子', link: `${path.main}bc03-0.1.8.0.0` },
              { text: '穀精草', link: `${path.main}bc03-0.1.9.0.0` },
              { text: '密蒙花', link: `${path.main}bc03-0.1.10.0.0` },
              { text: '青葙子', link: `${path.main}bc03-0.1.11.0.0` },
              { text: '夜明砂', link: `${path.main}bc03-0.1.12.0.0` },
              { text: '熊胆', link: `${path.main}bc03-0.1.13.0.0` },
              { text: '西瓜', link: `${path.main}bc03-0.1.14.0.0` },
            ],
          },
          {
            text: '第二节 清热燥湿药',
            link: `${path.main}bc03-0.2.0.0.0`,
            collapsed: true,
            items: [
              { text: '黄芩', link: `${path.main}bc03-0.2.1.0.0` },
              { text: '黄连', link: `${path.main}bc03-0.2.2.0.0` },
              { text: '黄柏', link: `${path.main}bc03-0.2.3.0.0` },
              { text: '龙胆草', link: `${path.main}bc03-0.2.4.0.0` },
              { text: '苦参', link: `${path.main}bc03-0.2.5.0.0` },
              { text: '白鲜皮', link: `${path.main}bc03-0.2.6.0.0` },
              { text: '秦皮', link: `${path.main}bc03-0.2.7.0.0` },
            ],
          },
          {
            text: '第三节清热凉血药',
            link: `${path.main}bc03-0.3.0.0.0`,
            collapsed: true,
            items: [
              { text: '犀角', link: `${path.main}bc03-0.3.1.0.0` },
              { text: '生地黄', link: `${path.main}bc03-0.3.2.0.0` },
              { text: '干地黄', link: `${path.main}bc03-0.3.3.0.0` },
              { text: '玄参', link: `${path.main}bc03-0.3.4.0.0` },
              { text: '牡丹皮', link: `${path.main}bc03-0.3.5.0.0` },
              { text: '紫草', link: `${path.main}bc03-0.3.6.0.0` },
              { text: '童便', link: `${path.main}bc03-0.3.7.0.0` },
              { text: '人中黄', link: `${path.main}bc03-0.3.8.0.0` },
              { text: '人中白', link: `${path.main}bc03-0.3.9.0.0` },
              { text: '芸苔', link: `${path.main}bc03-0.3.10.0.0` },
            ],
          },
          {
            text: '第四节清热解毒药',
            link: `${path.main}bc03-0.4.0.0.0`,
            collapsed: true,
            items: [
              { text: '金银花', link: `${path.main}bc03-0.4.1.0.0` },
              { text: '连翘', link: `${path.main}bc03-0.4.2.0.0` },
              { text: '蒲公英', link: `${path.main}bc03-0.4.3.0.0` },
              { text: '紫花地丁', link: `${path.main}bc03-0.4.4.0.0` },
              { text: '大青叶', link: `${path.main}bc03-0.4.5.0.0` },
              { text: '青黛', link: `${path.main}bc03-0.4.6.0.0` },
              { text: '败酱草', link: `${path.main}bc03-0.4.7.0.0` },
              { text: '土茯苓', link: `${path.main}bc03-0.4.8.0.0` },
              { text: '马勃', link: `${path.main}bc03-0.4.9.0.0` },
              { text: '山豆根', link: `${path.main}bc03-0.4.10.0.0` },
              { text: '射干', link: `${path.main}bc03-0.4.11.0.0` },
              { text: '白头翁', link: `${path.main}bc03-0.4.12.0.0` },
              { text: '马齿苋', link: `${path.main}bc03-0.4.13.0.0` },
              { text: '白蔹', link: `${path.main}bc03-0.4.14.0.0` },
              { text: '漏芦', link: `${path.main}bc03-0.4.15.0.0` },
              { text: '山慈姑', link: `${path.main}bc03-0.4.16.0.0` },
              { text: '绿豆', link: `${path.main}bc03-0.4.17.0.0` },
              { text: '菱', link: `${path.main}bc03-0.4.18.0.0` },
              { text: '橄揽', link: `${path.main}bc03-0.4.19.0.0` },
              { text: '梨', link: `${path.main}bc03-0.4.20.0.0` },
              { text: '甘蔗', link: `${path.main}bc03-0.4.21.0.0` },
              { text: '茶', link: `${path.main}bc03-0.4.22.0.0` },
              { text: '芭蕉根', link: `${path.main}bc03-0.4.23.0.0` },
              { text: '枳椇子', link: `${path.main}bc03-0.4.24.0.0` },
            ],
          },
          {
            text: '第五节清虚热药',
            link: `${path.main}bc03-0.5.0.0.0`,
            collapsed: true,
            items: [
              { text: '青蒿', link: `${path.main}bc03-0.5.1.0.0` },
              { text: '白薇', link: `${path.main}bc03-0.5.2.0.0` },
              { text: '地骨皮', link: `${path.main}bc03-0.5.3.0.0` },
              { text: '胡黄连', link: `${path.main}bc03-0.5.4.0.0` },
            ],
          },
          { text: '小结', link: `${path.main}bc03-0.6.0.0.0` },
        ],
      },
      {
        text: '第四章芳香化湿药',
        link: `${path.main}bc04`,
        collapsed: true,
        items: [
          { text: '藿香', link: `${path.main}bc04-0.0.1.0.0` },
          { text: '苍术', link: `${path.main}bc04-0.0.2.0.0` },
          { text: '厚朴', link: `${path.main}bc04-0.0.3.0.0` },
          { text: '砂仁', link: `${path.main}bc04-0.0.4.0.0` },
          { text: '白豆蔻', link: `${path.main}bc04-0.0.5.0.0` },
          { text: '草豆蔻', link: `${path.main}bc04-0.0.6.0.0` },
          { text: '附：草果', link: `${path.main}bc04-0.0.7.0.0` },
          { text: '小结', link: `${path.main}bc04-0.0.8.0.0` },
        ],
      },
      {
        text: '第五章利水渗湿药',
        link: `${path.main}bc05`,
        collapsed: true,
        items: [
          { text: '茯苓', link: `${path.main}bc05-0.0.1.0.0` },
          { text: '附：茯神', link: `${path.main}bc05-0.0.2.0.0` },
          { text: '猪苓', link: `${path.main}bc05-0.0.3.0.0` },
          { text: '泽泻', link: `${path.main}bc05-0.0.4.0.0` },
          { text: '薏苡仁', link: `${path.main}bc05-0.0.5.0.0` },
          { text: '车前草 车前子', link: `${path.main}bc05-0.0.6.0.0` },
          { text: '滑石', link: `${path.main}bc05-0.0.7.0.0` },
          { text: '木通', link: `${path.main}bc05-0.0.8.0.0` },
          { text: '通草', link: `${path.main}bc05-0.0.9.0.0` },
          { text: '萹蓄', link: `${path.main}bc05-0.0.10.0.0` },
          { text: '石苇', link: `${path.main}bc05-0.0.11.0.0` },
          { text: '瞿麦', link: `${path.main}bc05-0.0.12.0.0` },
          { text: '海金沙', link: `${path.main}bc05-0.0.13.0.0` },
          { text: '萆薢', link: `${path.main}bc05-0.0.14.0.0` },
          { text: '茵陈', link: `${path.main}bc05-0.0.15.0.0` },
          { text: '地肤子', link: `${path.main}bc05-0.0.16.0.0` },
          { text: '冬葵子', link: `${path.main}bc05-0.0.17.0.0` },
          { text: '冬瓜', link: `${path.main}bc05-0.0.18.0.0` },
          { text: '附：冬瓜皮', link: `${path.main}bc05-0.0.19.0.0` },
          { text: '赤小豆', link: `${path.main}bc05-0.0.20.0.0` },
          { text: '灯草', link: `${path.main}bc05-0.0.21.0.0` },
          { text: '淡竹叶', link: `${path.main}bc05-0.0.22.0.0` },
          { text: '鲤鱼', link: `${path.main}bc05-0.0.23.0.0` },
          { text: '小结', link: `${path.main}bc05-0.0.24.0.0` },
        ],
      },
      {
        text: '第六章祛风湿药',
        link: `${path.main}bc06`,
        collapsed: true,
        items: [
          { text: '独活', link: `${path.main}bc06-0.0.1.0.0` },
          { text: '威灵仙', link: `${path.main}bc06-0.0.2.0.0` },
          { text: '防己', link: `${path.main}bc06-0.0.3.0.0` },
          { text: '秦艽', link: `${path.main}bc06-0.0.4.0.0` },
          { text: '木瓜', link: `${path.main}bc06-0.0.5.0.0` },
          { text: '五加皮', link: `${path.main}bc06-0.0.6.0.0` },
          { text: '桑寄生', link: `${path.main}bc06-0.0.7.0.0` },
          { text: '白花蛇', link: `${path.main}bc06-0.0.8.0.0` },
          { text: '乌梢蛇', link: `${path.main}bc06-0.0.9.0.0` },
          { text: '蛇蜕', link: `${path.main}bc06-0.0.10.0.0` },
          { text: '虎骨', link: `${path.main}bc06-0.0.11.0.0` },
          { text: '豨莶草', link: `${path.main}bc06-0.0.12.0.0` },
          { text: '海桐皮', link: `${path.main}bc06-0.0.13.0.0` },
          { text: '原蚕沙', link: `${path.main}bc06-0.0.14.0.0` },
          { text: '松节', link: `${path.main}bc06-0.0.15.0.0` },
          { text: '络石藤', link: `${path.main}bc06-0.0.16.0.0` },
          { text: '桑枝', link: `${path.main}bc06-0.0.17.0.0` },
          { text: '石南叶', link: `${path.main}bc06-0.0.18.0.0` },
          { text: '天仙藤', link: `${path.main}bc06-0.0.19.0.0` },
          { text: '小结', link: `${path.main}bc06-0.0.20.0.0` },
        ],
      },
      {
        text: '第七章 温里药',
        link: `${path.main}bc07`,
        collapsed: true,
        items: [
          { text: '附子 附：乌头 天雄 ', link: `${path.main}bc07-0.1.0.0.0` },
          { text: '草乌头', link: `${path.main}bc07-0.2.0.0.0` },
          { text: '肉桂 桂心', link: `${path.main}bc07-0.3.0.0.0` },
          { text: '干姜 附：黑姜', link: `${path.main}bc07-0.4.0.0.0` },
          { text: '吴茱萸', link: `${path.main}bc07-0.5.0.0.0` },
          { text: '高良姜', link: `${path.main}bc07-0.6.0.0.0` },
          { text: '附：红豆蔻', link: `${path.main}bc07-0.6.1.0.0` },
          { text: '川椒', link: `${path.main}bc07-0.7.0.0.0` },
          { text: '附：椒目', link: `${path.main}bc07-0.7.1.0.0` },
          { text: '丁香', link: `${path.main}bc07-0.8.0.0.0` },
          { text: '附：母丁香', link: `${path.main}bc07-0.8.1.0.0` },
          { text: '茴香', link: `${path.main}bc07-0.9.0.0.0` },
          { text: '胡椒', link: `${path.main}bc07-0.10.0.0.0` },
          { text: '附：荜澄茄', link: `${path.main}bc07-0.10.1.0.0` },
          { text: '荜茇', link: `${path.main}bc07-0.11.0.0.0` },
          { text: '小结', link: `${path.main}bc07-0.12.0.0.0` },
        ],
      },
      {
        text: '第八章开窍药',
        link: `${path.main}bc08`,
        collapsed: true,
        items: [
          { text: '麝香', link: `${path.main}bc08-0.0.1.0.0` },
          { text: '牛黄', link: `${path.main}bc08-0.0.2.0.0` },
          { text: '冰片', link: `${path.main}bc08-0.0.3.0.0` },
          { text: '苏合香', link: `${path.main}bc08-0.0.4.0.0` },
          { text: '石菖蒲', link: `${path.main}bc08-0.0.5.0.0` },
          { text: '安息香', link: `${path.main}bc08-0.0.6.0.0` },
          { text: '小结', link: `${path.main}bc08-0.0.7.0.0` },
        ],
      },
      {
        text: '第九章安神药',
        link: `${path.main}bc09`,
        collapsed: true,
        items: [
          {
            text: '第一节重镇安神药',
            link: `${path.main}bc09-0.1.0.0.0`,
            collapsed: true,
            items: [
              { text: '朱砂', link: `${path.main}bc09-0.1.1.0.0` },
              { text: '磁石', link: `${path.main}bc09-0.1.2.0.0` },
              { text: '龙骨', link: `${path.main}bc09-0.1.3.0.0` },
              { text: '龙齿', link: `${path.main}bc09-0.1.4.0.0` },
              { text: '牡蛎', link: `${path.main}bc09-0.1.5.0.0` },
              { text: '紫石英', link: `${path.main}bc09-0.1.6.0.0` },
              { text: '金', link: `${path.main}bc09-0.1.7.0.0` },
              { text: '铁', link: `${path.main}bc09-0.1.8.0.0` },
              { text: '珍珠', link: `${path.main}bc09-0.1.9.0.0` },
              { text: '琥珀', link: `${path.main}bc09-0.1.10.0.0` },
            ],
          },
          {
            text: '第二节养心安神药',
            link: `${path.main}bc09-0.2.0.0.0`,
            collapsed: true,
            items: [
              { text: '酸枣仁', link: `${path.main}bc09-0.2.1.0.0` },
              { text: '柏子仁', link: `${path.main}bc09-0.2.2.0.0` },
              { text: '远志', link: `${path.main}bc09-0.2.3.0.0` },
              { text: '合欢皮', link: `${path.main}bc09-0.2.4.0.0` },
            ],
          },
          { text: '小结', link: `${path.main}bc09-0.2.5.0.0` },
        ],
      },
      {
        text: '第十章平肝息风药',
        link: `${path.main}bc10`,
        collapsed: true,
        items: [
          { text: '羚羊角', link: `${path.main}bc10-0.0.1.0.0` },
          { text: '石决明', link: `${path.main}bc10-0.0.2.0.0` },
          { text: '贝子', link: `${path.main}bc10-0.0.3.0.0` },
          { text: '代赭石', link: `${path.main}bc10-0.0.4.0.0` },
          { text: '钩藤钩', link: `${path.main}bc10-0.0.5.0.0` },
          { text: '天麻', link: `${path.main}bc10-0.0.6.0.0` },
          { text: '蚯蚓', link: `${path.main}bc10-0.0.7.0.0` },
          { text: '僵蚕', link: `${path.main}bc10-0.0.8.0.0` },
          { text: '全蝎', link: `${path.main}bc10-0.0.9.0.0` },
          { text: '蜈蚣', link: `${path.main}bc10-0.0.10.0.0` },
          { text: '小结', link: `${path.main}bc10-0.0.11.0.0` },
        ],
      },
      {
        text: '第十一章理气药',
        link: `${path.main}bc11`,
        collapsed: true,
        items: [
          { text: '陈皮', link: `${path.main}bc11-0.0.1.0.0` },
          { text: '青皮', link: `${path.main}bc11-0.0.2.0.0` },
          { text: '枳实、枳壳', link: `${path.main}bc11-0.0.3.0.0` },
          { text: '香附', link: `${path.main}bc11-0.0.4.0.0` },
          { text: '木香', link: `${path.main}bc11-0.0.5.0.0` },
          { text: '乌药', link: `${path.main}bc11-0.0.6.0.0` },
          { text: '佛手', link: `${path.main}bc11-0.0.7.0.0` },
          { text: '香橼', link: `${path.main}bc11-0.0.8.0.0` },
          { text: '沉香', link: `${path.main}bc11-0.0.9.0.0` },
          { text: '檀香', link: `${path.main}bc11-0.0.10.0.0` },
          { text: '紫檀', link: `${path.main}bc11-0.0.11.0.0` },
          { text: '川楝子', link: `${path.main}bc11-0.0.12.0.0` },
          { text: '荔枝核', link: `${path.main}bc11-0.0.13.0.0` },
          { text: '薤白', link: `${path.main}bc11-0.0.14.0.0` },
          { text: '大腹皮', link: `${path.main}bc11-0.0.15.0.0` },
          { text: '甘松香', link: `${path.main}bc11-0.0.16.0.0` },
          { text: '山柰', link: `${path.main}bc11-0.0.17.0.0` },
          { text: '刀豆', link: `${path.main}bc11-0.0.18.0.0` },
          { text: '柿干', link: `${path.main}bc11-0.0.19.0.0` },
          { text: '梅花', link: `${path.main}bc11-0.0.20.0.0` },
          { text: '小结', link: `${path.main}bc11-0.0.21.0.0` },
        ],
      },
      {
        text: '第十二章活血祛瘀药',
        link: `${path.main}bc12`,
        collapsed: true,
        items: [
          { text: '芎䓖', link: `${path.main}bc12-0.0.1.0.0` },
          { text: '延胡索', link: `${path.main}bc12-0.0.2.0.0` },
          { text: '郁金', link: `${path.main}bc12-0.0.3.0.0` },
          { text: '姜黄', link: `${path.main}bc12-0.0.4.0.0` },
          { text: '蓬莪术', link: `${path.main}bc12-0.0.5.0.0` },
          { text: '荆三棱', link: `${path.main}bc12-0.0.6.0.0` },
          { text: '丹参', link: `${path.main}bc12-0.0.7.0.0` },
          { text: '益母草', link: `${path.main}bc12-0.0.8.0.0` },
          { text: '泽兰', link: `${path.main}bc12-0.0.9.0.0` },
          { text: '桃仁', link: `${path.main}bc12-0.0.10.0.0` },
          { text: '红花', link: `${path.main}bc12-0.0.11.0.0` },
          { text: '鸡血藤', link: `${path.main}bc12-0.0.12.0.0` },
          { text: '乳香', link: `${path.main}bc12-0.0.13.0.0` },
          { text: '没药', link: `${path.main}bc12-0.0.14.0.0` },
          { text: '穿山甲', link: `${path.main}bc12-0.0.15.0.0` },
          { text: '王不留行', link: `${path.main}bc12-0.0.16.0.0` },
          { text: '皂角刺', link: `${path.main}bc12-0.0.17.0.0` },
          { text: '苏木', link: `${path.main}bc12-0.0.18.0.0` },
          { text: '刘寄奴', link: `${path.main}bc12-0.0.19.0.0` },
          { text: '自然铜', link: `${path.main}bc12-0.0.20.0.0` },
          { text: '牛膝', link: `${path.main}bc12-0.0.21.0.0` },
          { text: '五灵脂', link: `${path.main}bc12-0.0.22.0.0` },
          { text: '降真香', link: `${path.main}bc12-0.0.23.0.0` },
          { text: '凌霄花', link: `${path.main}bc12-0.0.24.0.0` },
          { text: '枫脂香', link: `${path.main}bc12-0.0.25.0.0` },
          { text: '马鞭草', link: `${path.main}bc12-0.0.26.0.0` },
          { text: '干漆', link: `${path.main}bc12-0.0.27.0.0` },
          { text: '小 结', link: `${path.main}bc12-0.0.28.0.0` },
          { text: '活血祛瘀药功用归纳简表', link: `${path.main}bc12-0.0.29.0.0` },
        ],
      },
      {
        text: '第十三章止血药',
        link: `${path.main}bc13`,
        collapsed: true,
        items: [
          { text: '大小蓟', link: `${path.main}bc13-0.0.1.0.0` },
          { text: '侧柏叶', link: `${path.main}bc13-0.0.2.0.0` },
          { text: '槐实', link: `${path.main}bc13-0.0.3.0.0` },
          { text: '地榆', link: `${path.main}bc13-0.0.4.0.0` },
          { text: '白茅根', link: `${path.main}bc13-0.0.5.0.0` },
          { text: '苎麻根', link: `${path.main}bc13-0.0.6.0.0` },
          { text: '藕', link: `${path.main}bc13-0.0.7.0.0` },
          { text: '仙鹤草', link: `${path.main}bc13-0.0.8.0.0` },
          { text: '白芨', link: `${path.main}bc13-0.0.9.0.0` },
          { text: '棕榈', link: `${path.main}bc13-0.0.10.0.0` },
          { text: '血余炭', link: `${path.main}bc13-0.0.11.0.0` },
          { text: '三七', link: `${path.main}bc13-0.0.12.0.0` },
          { text: '茜草', link: `${path.main}bc13-0.0.13.0.0` },
          { text: '蒲黄', link: `${path.main}bc13-0.0.14.0.0` },
          { text: '艾叶', link: `${path.main}bc13-0.0.15.0.0` },
          { text: '卷柏', link: `${path.main}bc13-0.0.16.0.0` },
          { text: '伏龙肝', link: `${path.main}bc13-0.0.17.0.0` },
          { text: '百草霜', link: `${path.main}bc13-0.0.18.0.0` },
          { text: '花乳石', link: `${path.main}bc13-0.0.19.0.0` },
          { text: '小结', link: `${path.main}bc13-0.0.20.0.0` },
          { text: '止血药功用归纳简表', link: `${path.main}bc13-0.0.21.0.0` },
        ],
      },
      {
        text: '第十四章消食药',
        link: `${path.main}bc14`,
        collapsed: true,
        items: [
          { text: '山楂', link: `${path.main}bc14-0.0.1.0.0` },
          { text: '麦芽', link: `${path.main}bc14-0.0.2.0.0` },
          { text: '榖芽', link: `${path.main}bc14-0.0.3.0.0` },
          { text: '神曲', link: `${path.main}bc14-0.0.4.0.0` },
          { text: '鸡内金', link: `${path.main}bc14-0.0.5.0.0` },
          { text: '莱菔(莱菔子)', link: `${path.main}bc14-0.0.6.0.0` },
          { text: '小结', link: `${path.main}bc14-0.0.7.0.0` },
          { text: '消食药功用归纳简表', link: `${path.main}bc14-0.0.8.0.0` },
        ],
      },
      {
        text: '第十五章驱虫药',
        link: `${path.main}bc15`,
        collapsed: true,
        items: [
          { text: '使君子', link: `${path.main}bc15-0.0.1.0.0` },
          { text: '槟榔', link: `${path.main}bc15-0.0.2.0.0` },
          { text: '雷丸', link: `${path.main}bc15-0.0.3.0.0` },
          { text: '鹤虱', link: `${path.main}bc15-0.0.4.0.0` },
          { text: '芜荑', link: `${path.main}bc15-0.0.5.0.0` },
          { text: '榧实', link: `${path.main}bc15-0.0.6.0.0` },
          { text: '贯众', link: `${path.main}bc15-0.0.7.0.0` },
          { text: '大蒜', link: `${path.main}bc15-0.0.8.0.0` },
          { text: '小结', link: `${path.main}bc15-0.0.9.0.0` },
        ],
      },
      {
        text: '第十六章化痰止咳平喘药',
        link: `${path.main}bc16`,
        collapsed: true,
        items: [
          {
            text: '第一节温化寒痰药',
            link: `${path.main}bc16-0.1.0.0.0`,
            collapsed: true,
            items: [
              { text: '半夏', link: `${path.main}bc16-0.1.1.0.0` },
              { text: '天南星', link: `${path.main}bc16-0.1.2.0.0` },
              { text: '白附子', link: `${path.main}bc16-0.1.3.0.0` },
              { text: '白芥子', link: `${path.main}bc16-0.1.4.0.0` },
              { text: '旋覆花', link: `${path.main}bc16-0.1.5.0.0` },
              { text: '白前', link: `${path.main}bc16-0.1.6.0.0` },
              { text: '皂角 肥皂荚', link: `${path.main}bc16-0.1.7.0.0` },
            ],
          },
          {
            text: '第二节清化热痰药',
            link: `${path.main}bc16-0.2.0.0.0`,
            collapsed: true,
            items: [
              { text: '前胡', link: `${path.main}bc16-0.2.1.0.0` },
              { text: '桔梗', link: `${path.main}bc16-0.2.2.0.0` },
              { text: '贝母', link: `${path.main}bc16-0.2.3.0.0` },
              { text: '瓜蒌', link: `${path.main}bc16-0.2.4.0.0` },
              { text: '竹茹', link: `${path.main}bc16-0.2.5.0.0` },
              { text: '竹沥', link: `${path.main}bc16-0.2.6.0.0` },
              { text: '荆沥', link: `${path.main}bc16-0.2.7.0.0` },
              { text: '天竺黄', link: `${path.main}bc16-0.2.8.0.0` },
              { text: '礞石', link: `${path.main}bc16-0.2.9.0.0` },
              { text: '浮海石', link: `${path.main}bc16-0.2.10.0.0` },
              { text: '海蛤壳', link: `${path.main}bc16-0.2.11.0.0` },
              { text: '瓦楞子', link: `${path.main}bc16-0.2.12.0.0` },
              { text: '海藻', link: `${path.main}bc16-0.2.13.0.0` },
              { text: '昆布', link: `${path.main}bc16-0.2.14.0.0` },
              { text: '胖大海', link: `${path.main}bc16-0.2.15.0.0` },
              { text: '荸荠', link: `${path.main}bc16-0.2.16.0.0` },
              { text: '荠苨', link: `${path.main}bc16-0.2.17.0.0` },
              { text: '胡桐泪', link: `${path.main}bc16-0.2.18.0.0` },
            ],
          },
          {
            text: '第三节止咳平喘药',
            link: `${path.main}bc16-0.3.0.0.0`,
            collapsed: true,
            items: [
              { text: '杏仁', link: `${path.main}bc16-0.3.1.0.0` },
              { text: '紫菀', link: `${path.main}bc16-0.3.3.0.0` },
              { text: '款冬花', link: `${path.main}bc16-0.3.4.0.0` },
              { text: '百部', link: `${path.main}bc16-0.3.5.0.0` },
              { text: '桑白皮', link: `${path.main}bc16-0.3.6.0.0` },
              { text: '葶苈子', link: `${path.main}bc16-0.3.7.0.0` },
              { text: '马兜铃', link: `${path.main}bc16-0.3.8.0.0` },
              { text: '枇杷叶', link: `${path.main}bc16-0.3.9.0.0` },
            ],
          },
          { text: '小 结', link: `${path.main}bc16-0.4.0.0.0` },
        ],
      },
      {
        text: '第十七章补益药',
        link: `${path.main}bc17`,
        collapsed: true,
        items: [
          {
            text: '第一节补气药',
            link: `${path.main}bc17-0.1.0.0.0`,
            collapsed: true,
            items: [
              { text: '人参 人参芦', link: `${path.main}bc17-0.1.1.0.0` },
              { text: '党参', link: `${path.main}bc17-0.1.2.0.0` },
              { text: '西洋参', link: `${path.main}bc17-0.1.2.0.0.xys` },
              { text: '太子参', link: `${path.main}bc17-0.1.3.0.0` },
              { text: '黄芪', link: `${path.main}bc17-0.1.4.0.0` },
              { text: '白术', link: `${path.main}bc17-0.1.5.0.0` },
              { text: '山药', link: `${path.main}bc17-0.1.6.0.0` },
              { text: '白扁豆', link: `${path.main}bc17-0.1.7.0.0` },
              { text: '甘草', link: `${path.main}bc17-0.1.8.0.0` },
              { text: '大枣', link: `${path.main}bc17-0.1.9.0.0` },
            ],
          },
          {
            text: '第二节补阳药',
            link: `${path.main}bc17-0.2.0.0.0`,
            collapsed: true,
            items: [
              { text: '鹿茸', link: `${path.main}bc17-0.2.1.0.0` },
              { text: '巴戟天', link: `${path.main}bc17-0.2.2.0.0` },
              { text: '肉苁蓉', link: `${path.main}bc17-0.2.3.0.0` },
              { text: '锁阳', link: `${path.main}bc17-0.2.4.0.0` },
              { text: '淫羊藿', link: `${path.main}bc17-0.2.5.0.0` },
              { text: '仙茅', link: `${path.main}bc17-0.2.6.0.0` },
              { text: '菟丝子', link: `${path.main}bc17-0.2.7.0.0` },
              { text: '蒺藜子', link: `${path.main}bc17-0.2.7.2.0.0` },
              { text: '破故纸', link: `${path.main}bc17-0.2.8.0.0` },
              { text: '益智仁', link: `${path.main}bc17-0.2.9.0.0` },
              { text: '杜仲', link: `${path.main}bc17-0.2.10.0.0` },
              { text: '续断', link: `${path.main}bc17-0.2.10.0.xd` },
              { text: '狗脊', link: `${path.main}bc17-0.2.11.0.0` },
              { text: '骨碎补', link: `${path.main}bc17-0.2.12.0.0` },
              { text: '胡芦巴', link: `${path.main}bc17-0.2.13.0.0` },
              { text: '冬虫夏草', link: `${path.main}bc17-0.2.14.0.0` },
              { text: '蛤蚧', link: `${path.main}bc17-0.2.15.0.0` },
              { text: '胡桃', link: `${path.main}bc17-0.2.16.0.0` },
              { text: '紫河车', link: `${path.main}bc17-0.2.17.0.0` },
              { text: '海狗肾', link: `${path.main}bc17-0.2.18.0.0` },
              { text: '韭菜 韭子', link: `${path.main}bc17-0.2.19.0.0` },
              { text: '阳起石', link: `${path.main}bc17-0.2.20.0.0` },
              { text: '海马', link: `${path.main}bc17-0.2.21.0.0` },
              { text: '羊肉', link: `${path.main}bc17-0.2.22.0.0` },
            ],
          },
          {
            text: '第三节补血药',
            link: `${path.main}bc17-0.3.0.0.0`,
            collapsed: true,
            items: [
              { text: '熟地黄', link: `${path.main}bc17-0.3.1.0.0` },
              { text: '何首乌', link: `${path.main}bc17-0.3.2.0.0` },
              { text: '当归', link: `${path.main}bc17-0.3.3.0.0` },
              { text: '白芍药 赤芍药', link: `${path.main}bc17-0.3.4.0.0` },
              { text: '阿胶', link: `${path.main}bc17-0.3.5.0.0` },
              { text: '黄明胶', link: `${path.main}bc17-0.3.6.0.0` },
              { text: '龙眼肉', link: `${path.main}bc17-0.3.7.0.0` },
            ],
          },
          {
            text: '第四节补阴药',
            link: `${path.main}bc17-0.4.0.0.0`,
            collapsed: true,
            items: [
              { text: '沙参', link: `${path.main}bc17-0.4.1.0.0` },
              { text: '麦门冬', link: `${path.main}bc17-0.4.2.0.0` },
              { text: '天门冬', link: `${path.main}bc17-0.4.3.0.0` },
              { text: '石斛', link: `${path.main}bc17-0.4.4.0.0` },
              { text: '萎蕤', link: `${path.main}bc17-0.4.5.0.0` },
              { text: '黄精', link: `${path.main}bc17-0.4.6.0.0` },
              { text: '百合', link: `${path.main}bc17-0.4.7.0.0` },
              { text: '枸杞子 枸杞叶', link: `${path.main}bc17-0.4.8.0.0` },
              { text: '旱莲草', link: `${path.main}bc17-0.4.9.0.0` },
              { text: '女贞子', link: `${path.main}bc17-0.4.10.0.0` },
              { text: '桑椹', link: `${path.main}bc17-0.4.11.0.0` },
              { text: '楮实', link: `${path.main}bc17-0.4.12.0.0` },
              { text: '落花生', link: `${path.main}bc17-0.4.13.0.0` },
              { text: '龟版', link: `${path.main}bc17-0.4.14.0.0` },
              { text: '鳖甲', link: `${path.main}bc17-0.4.15.0.0` },
              { text: '胡麻', link: `${path.main}bc17-0.4.16.0.0` },
              { text: '乌骨鸡', link: `${path.main}bc17-0.4.17.0.0` },
              { text: '黑大豆', link: `${path.main}bc17-0.4.18.0.0` },
            ],
          },
          {
            text: '小结',
            link: `${path.main}bc17-0.5.0.0.0`,
            collapsed: true,
            items: [{ text: '补益药功用归纳简表', link: `${path.main}bc17-0.5.1.0.0` }],
          },
        ],
      },
      {
        text: '第十八章收敛药',
        link: `${path.main}bc18`,
        collapsed: true,
        items: [
          { text: '山茱萸', link: `${path.main}bc18-0.0.1.0.0` },
          { text: '五味子', link: `${path.main}bc18-0.0.2.0.0` },
          { text: '五倍子', link: `${path.main}bc18-0.0.3.0.0` },
          { text: '小麦', link: `${path.main}bc18-0.0.4.0.0` },
          { text: '乌梅', link: `${path.main}bc18-0.0.5.0.0` },
          { text: '肉豆蔻', link: `${path.main}bc18-0.0.6.0.0` },
          { text: '诃子', link: `${path.main}bc18-0.0.7.0.0` },
          { text: '赤石脂', link: `${path.main}bc18-0.0.8.0.0` },
          { text: '禹余粮', link: `${path.main}bc18-0.0.9.0.0` },
          { text: '石榴皮', link: `${path.main}bc18-0.0.10.0.0` },
          { text: '海螵蛸', link: `${path.main}bc18-0.0.11.0.0` },
          { text: '芡实', link: `${path.main}bc18-0.0.12.0.0` },
          { text: '莲子', link: `${path.main}bc18-0.0.13.0.0` },
          { text: '莲蕊鬚', link: `${path.main}bc18-0.0.14.0.0` },
          { text: '荷叶', link: `${path.main}bc18-0.0.15.0.0` },
          { text: '金樱子', link: `${path.main}bc18-0.0.16.0.0` },
          { text: '覆盆子', link: `${path.main}bc18-0.0.17.0.0` },
          { text: '桑螵蛸', link: `${path.main}bc18-0.0.18.0.0` },
          { text: '椿樗白皮', link: `${path.main}bc18-0.0.19.0.0` },
          { text: '白果', link: `${path.main}bc18-0.0.20.0.0` },
          { text: '罂粟壳', link: `${path.main}bc18-0.0.21.0.0` },
          { text: '剌猬皮', link: `${path.main}bc18-0.0.22.0.0` },
          { text: '没石子', link: `${path.main}bc18-0.0.23.0.0` },
          { text: '小结', link: `${path.main}bc18-0.0.24.0.0` },
        ],
      },
      {
        text: '第十九章涌吐药',
        link: `${path.main}bc19`,
        collapsed: true,
        items: [
          { text: '瓜蒂', link: `${path.main}bc19-0.0.1.0.0` },
          { text: '常山', link: `${path.main}bc19-0.0.2.0.0` },
          { text: '胆矾', link: `${path.main}bc19-0.0.3.0.0` },
          { text: '藜芦', link: `${path.main}bc19-0.0.4.0.0` },
          { text: '小结', link: `${path.main}bc19-0.0.5.0.0` },
        ],
      },
      {
        text: '第二十章外用药及其他',
        link: `${path.main}bc20`,
        collapsed: true,
        items: [
          { text: '雄黄', link: `${path.main}bc20-0.1.0.0.0` },
          { text: '石硫黄', link: `${path.main}bc20-0.2.0.0.0` },
          { text: '砒石', link: `${path.main}bc20-0.3.0.0.0` },
          { text: '水银', link: `${path.main}bc20-0.4.0.0.0` },
          { text: '轻粉', link: `${path.main}bc20-0.5.0.0.0` },
          { text: '铅', link: `${path.main}bc20-0.6.0.0.0` },
          { text: '密陀僧', link: `${path.main}bc20-0.7.0.0.0` },
          { text: '硼砂', link: `${path.main}bc20-0.8.0.0.0` },
          { text: '炉甘石', link: `${path.main}bc20-0.9.0.0.0` },
          { text: '明矾', link: `${path.main}bc20-0.10.0.0.0` },
          { text: '皂矾', link: `${path.main}bc20-0.11.0.0.0` },
          { text: '斑蝥', link: `${path.main}bc20-0.12.0.0.0` },
          { text: '蟾蜍', link: `${path.main}bc20-0.13.0.0.0` },
          { text: '木鳖子', link: `${path.main}bc20-0.14.0.0.0` },
          { text: '附：马钱子', link: `${path.main}bc20-0.14.1.0.0` },
          { text: '血竭', link: `${path.main}bc20-0.15.0.0.0` },
          { text: '樟脑', link: `${path.main}bc20-0.16.0.0.0` },
          { text: '大风子', link: `${path.main}bc20-0.17.0.0.0` },
          { text: '蛇床子', link: `${path.main}bc20-0.18.0.0.0` },
          { text: '木槿皮', link: `${path.main}bc20-0.19.0.0.0` },
          { text: '丝瓜', link: `${path.main}bc20-0.20.0.0.0` },
          { text: '孩儿茶', link: `${path.main}bc20-0.21.0.0.0` },
          { text: '阿魏', link: `${path.main}bc20-0.22.0.0.0` },
          { text: '露蜂房', link: `${path.main}bc20-0.23.0.0.0` },
          { text: '小结', link: `${path.main}bc20-0.24.0.0.0` },
        ],
      },
    ],
  },
  { text: '补充药物归纳表', link: `${path.main}bc21bcyw` },
  { text: '本书引用方剂索引', link: `${path.main}bc21fjsy` },
  { text: '电子版录入与校对', link: `${path.main}dzb` },
];

export { sidebar as bc };
