const path = {
  main: '/gmzyjc/ok/zjx/',
};

const sidebar = [
  { text: '《针灸学-下》' },
  { text: '下篇 治疗', link: `${path.main}zjx1.1` },
  {
    text: '第一章  治疗总论',
    link: `${path.main}zjx1.1-1.0.0.0.0`,
    collapsed: true,
    items: [
      { text: '笫一节  针灸治病原理', link: `${path.main}zjx1.1-1.1.0.0.0` },
      { text: '第二节  针灸治则', link: `${path.main}zjx1.2` },
      { text: '第三节  八法在针灸临床上的运用', link: `${path.main}zjx1.3` },
      {
        text: '第四节辨证立法',
        link: `${path.main}zjx1.4`,
        collapsed: true,
        items: [
          { text: '一、八纲辨证与针灸', link: `${path.main}zjx1.4-0.0.1.0.0` },
          { text: '二、脏腑经络辨证与针灸', link: `${path.main}zjx1.4-0.0.2.0.0` },
          { text: '〔临床应用〕', link: `${path.main}zjx1.4-0.0.3.0.0` },
        ],
      },
      {
        text: '第五节  特定穴的应用',
        link: `${path.main}zjx1.5`,
        collapsed: true,
        items: [
          { text: '一、五输穴的应用', link: `${path.main}zjx1.5-0.0.1.0.0` },
          { text: '二、原穴、络穴的应用', link: `${path.main}zjx1.5-0.0.2.0.0` },
          { text: '三、俞、募穴的应用', link: `${path.main}zjx1.5-0.0.3.0.0` },
          { text: '四、八脉交会穴的应用', link: `${path.main}zjx1.5-0.0.4.0.0` },
          { text: '五、八会穴的应用', link: `${path.main}zjx1.5-0.0.5.0.0` },
          { text: '六、郄穴的应用', link: `${path.main}zjx1.5-0.0.6.0.0` },
          { text: '七、下合穴的应用', link: `${path.main}zjx1.5-0.0.7.0.0` },
          { text: '八、交会穴的应用', link: `${path.main}zjx1.5-0.0.8.0.0` },
          { text: '〔临床应用〕', link: `${path.main}zjx1.5-0.0.9.0.0` },
        ],
      },
      { text: '第六节  配方与选穴', link: `${path.main}zjx1.6`, collapsed: true, items: [] },
      { text: '一、配方种类', link: `${path.main}zjx1.6-0.0.1.0.0` },
      { text: '二、配方原则', link: `${path.main}zjx1.6-0.0.2.0.0` },
      {
        text: '三、配方方法',
        link: `${path.main}zjx1.6-0.0.3.0.0`,
        collapsed: true,
        items: [
          { text: '（一）前后配穴法', link: `${path.main}zjx1.6-0.0.3.1.0` },
          { text: '（二）上下配穴法', link: `${path.main}zjx1.6-0.0.3.2.0` },
          { text: '（三）左右配穴法', link: `${path.main}zjx1.6-0.0.3.3.0` },
          { text: '（四）表里配穴法', link: `${path.main}zjx1.6-0.0.3.4.0` },
          { text: '（五）本经配穴法', link: `${path.main}zjx1.6-0.0.3.5.0` },
          { text: '（六）远近配穴法', link: `${path.main}zjx1.6-0.0.3.6.0` },
          { text: '（七）脏象配穴法', link: `${path.main}zjx1.6-0.0.3.7.0` },
          { text: '（八）对症配穴法', link: `${path.main}zjx1.6-0.0.3.8.0` },
          { text: '（九）辨证配穴法', link: `${path.main}zjx1.6-0.0.3.9.0` },
          {
            text: '（十）按时选穴配方法  此法包括流注与灵龟二法。',
            link: `${path.main}zjx1.6-0.0.3.10.0`,
            collapsed: true,
            items: [
              { text: '子午流注开穴针法', link: `${path.main}zjx1.6-0.0.3.10.1` },
              { text: '灵龟八法', link: `${path.main}zjx1.6-0.0.3.10.2` },
            ],
          },
        ],
      },
      { text: '四、配方时应注意的问题', link: `${path.main}zjx1.6-0.0.4.0.0` },
      { text: '〔临床应用〕', link: `${path.main}zjx1.6-0.0.5.0.0` },
      {
        text: '第七节  症状治疗取穴',
        link: `${path.main}zjx1.7`,
        collapsed: true,
        items: [
          {
            text: '一、内科症状',
            link: `${path.main}zjx1.7-0.0.1.0.0`,
            collapsed: true,
            items: [
              { text: '（一）全身症状', link: `${path.main}zjx1.7-0.0.1.1.0` },
              { text: '（二）头项症状', link: `${path.main}zjx1.7-0.0.1.2.0` },
              { text: '（三）胸胁症状', link: `${path.main}zjx1.7-0.0.1.3.0` },
              { text: '（四）腹部症状', link: `${path.main}zjx1.7-0.0.1.4.0` },
              { text: '（五）背腰症状', link: `${path.main}zjx1.7-0.0.1.5.0` },
              { text: '（六）四肢症状', link: `${path.main}zjx1.7-0.0.1.6.0` },
              { text: '（七）二阴症状', link: `${path.main}zjx1.7-0.0.1.7.0` },
            ],
          },
          { text: '二、妇科症状', link: `${path.main}zjx1.7-0.0.2.0.0` },
          { text: '三、儿科症状', link: `${path.main}zjx1.7-0.0.3.0.0` },
          { text: '四、外科症状', link: `${path.main}zjx1.7-0.0.4.0.0` },
          { text: '〔临床应用〕', link: `${path.main}zjx1.7-0.0.5.0.0` },
        ],
      },
    ],
  },
  {
    text: '第二章 治疗各论',
    link: `${path.main}zjx2.1.1`,
    collapsed: true,
    items: [
      {
        text: '第一节  内科疾病',
        link: `${path.main}zjx2.1.1-0.1.0.0.0`,
        collapsed: true,
        items: [
          { text: '中风', link: `${path.main}zjx2.1.1-0.1.1.0.0` },
          { text: '感冒', link: `${path.main}zjx2.1.1-0.1.2.0.0` },
          { text: '中暑', link: `${path.main}zjx2.1.1-0.1.3.0.0` },
          { text: '疟疾', link: `${path.main}zjx2.1.1-0.1.4.0.0` },
          { text: '咳嗽', link: `${path.main}zjx2.1.1-0.1.5.0.0` },
          { text: '哮喘', link: `${path.main}zjx2.1.1-0.1.6.0.0` },
          { text: '肺痨', link: `${path.main}zjx2.1.1-0.1.7.0.0` },
          { text: '呕吐 附：呃逆', link: `${path.main}zjx2.1.2-0.0.1.0.0` },
          { text: '噎膈 附：反胃', link: `${path.main}zjx2.1.2-0.0.2.0.0` },
          { text: '胃痛', link: `${path.main}zjx2.1.2-0.0.3.0.0` },
          { text: '腹痛', link: `${path.main}zjx2.1.2-0.0.4.0.0` },
          { text: '泄泻', link: `${path.main}zjx2.1.2-0.0.5.0.0` },
          { text: '痢疾', link: `${path.main}zjx2.1.2-0.0.6.0.0` },
          { text: '便秘', link: `${path.main}zjx2.1.2-0.0.7.0.0` },
          { text: '脱肛', link: `${path.main}zjx2.1.2-0.0.8.0.0` },
          { text: '胁痛', link: `${path.main}zjx2.1.3-0.0.1.0.0` },
          { text: '黄疸', link: `${path.main}zjx2.1.3-0.0.2.0.0` },
          { text: '水肿', link: `${path.main}zjx2.1.3-0.0.3.0.0` },
          { text: '惊悸', link: `${path.main}zjx2.1.3-0.0.4.0.0` },
          { text: '不寐', link: `${path.main}zjx2.1.3-0.0.5.0.0` },
          { text: '郁证', link: `${path.main}zjx2.1.3-0.0.6.0.0` },
          { text: '淋证', link: `${path.main}zjx2.1.3-0.0.7.0.0` },
          { text: '癫狂', link: `${path.main}zjx2.1.3-0.0.8.0.0` },
          { text: '痫证', link: `${path.main}zjx2.1.3-0.0.9.0.0` },
          { text: '癃闭', link: `${path.main}zjx2.1.3-0.0.10.0.0` },
          { text: '遗精 附：阳痿', link: `${path.main}zjx2.1.3-0.0.11.0.0` },
          { text: '疝气', link: `${path.main}zjx2.1.3-0.0.12.0.0` },
          { text: '头痛', link: `${path.main}zjx2.1.4-0.0.1.0.0` },
          { text: '面痛', link: `${path.main}zjx2.1.4-0.0.2.0.0` },
          { text: '面瘫', link: `${path.main}zjx2.1.4-0.0.3.0.0` },
          { text: '眩晕', link: `${path.main}zjx2.1.4-0.0.4.0.0` },
          { text: '痹证  附：坐骨神经痛', link: `${path.main}zjx2.1.4-0.0.5.0.0` },
          { text: '痿证 附：多发性神经炎', link: `${path.main}zjx2.1.4-0.0.6.0.0` },
          { text: '腰痛', link: `${path.main}zjx2.1.4-0.0.7.0.0` },
          { text: '落枕', link: `${path.main}zjx2.1.4-0.0.8.0.0` },
          { text: '消渴', link: `${path.main}zjx2.1.4-0.0.9.0.0` },
        ],
      },
      {
        text: '第二节  外科疾病',
        link: `${path.main}zjx2.2`,
        collapsed: true,
        items: [
          { text: '疔疮', link: `${path.main}zjx2.2-0.0.1.0.0` },
          { text: '乳痈  附：乳癖', link: `${path.main}zjx2.2-0.0.2.0.0` },
          { text: '肠痈', link: `${path.main}zjx2.2-0.0.3.0.0` },
          { text: '痔疮', link: `${path.main}zjx2.2-0.0.4.0.0` },
          { text: '瘰疬', link: `${path.main}zjx2.2-0.0.5.0.0` },
          { text: '瘿气', link: `${path.main}zjx2.2-0.0.6.0.0` },
          { text: '丹毒', link: `${path.main}zjx2.2-0.0.7.0.0` },
          { text: '蛇丹', link: `${path.main}zjx2.2-0.0.8.0.0` },
          { text: '扁平疣', link: `${path.main}zjx2.2-0.0.9.0.0` },
          { text: '牛皮癣', link: `${path.main}zjx2.2-0.0.10.0.0` },
          { text: '破伤风', link: `${path.main}zjx2.2-0.0.11.0.0` },
          { text: '扭伤', link: `${path.main}zjx2.2-0.0.12.0.0` },
          { text: '风疹', link: `${path.main}zjx2.2-0.0.13.0.0` },
          { text: '斑秃', link: `${path.main}zjx2.2-0.0.14.0.0` },
        ],
      },
      {
        text: '第三节  妇科疾病',
        link: `${path.main}zjx2.3`,
        collapsed: true,
        items: [
          { text: '月经不调', link: `${path.main}zjx2.3-0.0.1.0.0` },
          { text: '痛经', link: `${path.main}zjx2.3-0.0.2.0.0` },
          { text: '经闭', link: `${path.main}zjx2.3-0.0.3.0.0` },
          { text: '崩漏', link: `${path.main}zjx2.3-0.0.4.0.0` },
          { text: '绝经前后诸证', link: `${path.main}zjx2.3-0.0.5.0.0` },
          { text: '带下病', link: `${path.main}zjx2.3-0.0.6.0.0` },
          { text: '妊娠恶阻', link: `${path.main}zjx2.3-0.0.7.0.0` },
          { text: '滞产', link: `${path.main}zjx2.3-0.0.8.0.0` },
          { text: '产后腹痛', link: `${path.main}zjx2.3-0.0.9.0.0` },
          { text: '产后血晕', link: `${path.main}zjx2.3-0.0.10.0.0` },
          { text: '乳少', link: `${path.main}zjx2.3-0.0.11.0.0` },
          { text: '阴挺', link: `${path.main}zjx2.3-0.0.12.0.0` },
          { text: '不孕', link: `${path.main}zjx2.3-0.0.13.0.0` },
        ],
      },
      {
        text: '第四节  儿科疾病',
        link: `${path.main}zjx2.4`,
        collapsed: true,
        items: [
          { text: '顿咳', link: `${path.main}zjx2.4-0.0.1.0.0` },
          { text: '小儿泄泻', link: `${path.main}zjx2.4-0.0.2.0.0` },
          { text: '疳疾', link: `${path.main}zjx2.4-0.0.3.0.0` },
          { text: '急惊风  附：慢惊风', link: `${path.main}zjx2.4-0.0.4.0.0` },
          { text: '小儿痿证', link: `${path.main}zjx2.4-0.0.5.0.0` },
          { text: '小儿遗尿', link: `${path.main}zjx2.4-0.0.6.0.0` },
          { text: '痄腮', link: `${path.main}zjx2.4-0.0.7.0.0` },
        ],
      },
      {
        text: '第五节五官疾病',
        link: `${path.main}zjx2.5`,
        collapsed: true,
        items: [
          { text: '针 眼', link: `${path.main}zjx2.5-0.0.1.0.0` },
          { text: '目赤肿痛', link: `${path.main}zjx2.5-0.0.2.0.0` },
          { text: '眼睑下垂', link: `${path.main}zjx2.5-0.0.3.0.0` },
          { text: '迎风流泪', link: `${path.main}zjx2.5-0.0.5.0.0` },
          { text: '近 视', link: `${path.main}zjx2.5-0.0.6.0.0` },
          { text: '斜 视', link: `${path.main}zjx2.5-0.0.7.0.0` },
          { text: '青盲', link: `${path.main}zjx2.5-0.0.8.0.0` },
          { text: '耳鸣耳聋', link: `${path.main}zjx2.5-0.0.9.0.0` },
          { text: '聋 哑', link: `${path.main}zjx2.5-0.0.10.0.0` },
          { text: '聤耳', link: `${path.main}zjx2.5-0.0.11.0.0` },
          { text: '鼻渊', link: `${path.main}zjx2.5-0.0.12.0.0` },
          { text: '鼻 衄', link: `${path.main}zjx2.5-0.0.13.0.0` },
          { text: '牙痛', link: `${path.main}zjx2.5-0.0.14.0.0` },
          { text: '咽喉肿痛', link: `${path.main}zjx2.5-0.0.15.0.0` },
        ],
      },
      {
        text: '第六节    急重症',
        link: `${path.main}zjx2.6`,
        collapsed: true,
        items: [
          { text: '高热', link: `${path.main}zjx2.6-0.0.1.0.0` },
          { text: '厥证', link: `${path.main}zjx2.6-0.0.2.0.0` },
          { text: '痉证', link: `${path.main}zjx2.6-0.0.3.0.0` },
          { text: '脱证', link: `${path.main}zjx2.6-0.0.4.0.0` },
          { text: '出血', link: `${path.main}zjx2.6-0.0.5.0.0` },
          { text: '剧痛证', link: `${path.main}zjx2.6-0.0.6.0.0` },
        ],
      },
    ],
  },
  {
    text: '附篇    参考资料',
    link: `${path.main}zjx3`,
    collapsed: true,
    items: [
      {
        text: '一、针灸文献节录',
        link: `${path.main}zjx3-0.1.0.0.0`,
        collapsed: true,
        items: [
          { text: '（一）《灵枢•九针十二原》①（节选）', link: `${path.main}zjx3-0.1.1.0.0` },
          { text: '（二）《灵枢•小针解》①（全文）', link: `${path.main}zjx3-0.1.2.0.0` },
          { text: '（三）《灵枢•本输》①（节选）', link: `${path.main}zjx3-0.1.3.0.0` },
          { text: '（四）《灵枢•官能》（节选）', link: `${path.main}zjx3-0.1.4.0.0` },
          { text: '（五）《素问•缪刺篇》（节选）', link: `${path.main}zjx3-0.1.5.0.0` },
        ],
      },
      {
        text: '二、针灸歌赋辑要',
        link: `${path.main}zjx3-0.2.0.0.0`,
        collapsed: true,
        items: [
          { text: '（一）《标幽赋》①', link: `${path.main}zjx3-0.2.1.0.0` },
          { text: '（二）《百症赋》①', link: `${path.main}zjx3-0.2.2.0.0` },
          { text: '（三）《玉龙歌》①', link: `${path.main}zjx3-0.2.3.0.0` },
          { text: '（四）《通玄指要赋》①', link: `${path.main}zjx3-0.2.4.0.0` },
          { text: '（五）《行针指要赋》', link: `${path.main}zjx3-0.2.5.0.0` },
          { text: '（六）《四总穴歌》', link: `${path.main}zjx3-0.2.6.0.0` },
          { text: '（七）《回阳九针歌》', link: `${path.main}zjx3-0.2.7.0.0` },
          { text: '（八）《马丹阳①天星②十二穴治杂病歌》', link: `${path.main}zjx3-0.2.8.0.0` },
        ],
      },
    ],
  },
  { text: '电子版录入与校对', link: `${path.main}dzb` },
];

export { sidebar as zjx };
